### ISSUE TITLE
can't download electron well

### ISSUE THREAD

**Issue by CracKerMe** [electron/electron-quick-start#101]
i try to use the VPN ,but failed. and the version is 1.4.4    am i wrong ?

**Comment by zeke** [comment]
Please share the OS you're using, and the full failure output you see when you run `npm install`

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment https://github.com/electron/electron-quick-start/issues/101#issuecomment-261612749. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
