### ISSUE TITLE
Can't install electron quick start

### ISSUE THREAD

**Issue by deidyomega** [electron/electron-quick-start#103]
$ nodejs --version
v6.9.1

$ npm install
(no return, appears successful)

$ npm start
(Lots of errors, but same in attached log)

DEBUG LOG:
[npm-debug.txt](https://github.com/electron/electron-quick-start/files/573554/npm-debug.txt)

**Comment by deidyomega** [comment]
Also note:

Just running:
$ electron .

Works fine, however npm start fails.

**Comment by yechenchao** [comment]
Yes, I have encountered the same problem

**Comment by yechenchao** [comment]
Just found a solution, electron needs to be installed first using below command:
npm install electron --save-dev
then, npm install && npm start

**Comment by adamschnaare** [comment]
Similar issue here. I get the following error:
```shell
app.on('ready', createWindow)
   ^
TypeError: Cannot read property 'on' of undefined
```
@yechenchao , above solution doesn't seem to work for me. Electron is installed, but still no dice.

**Comment by zeke** [comment]
What is the output of `npm ls electron` ?

**Comment by deidyomega** [comment]
hi @zeke I got frusterated with the code, and deleted the entire directory.

However when I did a git pull, and ran `npm start`

The code worked fine.

**Comment by adamschnaare** [comment]
Just did what @deidyomega did and it worked for me as well. Very odd, but glad it is working.

**Comment by zeke** [comment]
Glad you all worked it out! Closing.
