### ISSUE TITLE
npm install fails with Node v7.1.0

### ISSUE THREAD

**Issue by JimDaly** [electron/electron-quick-start#104]
Sorry, didn't catch details of error, but uninstalling node and re-installing with v6.9.1 fixed the problem.
Other than [electron.atom.io](http://electron.atom.io/)  saying 'Node: 6.5.0', I couldn't find details about what versions of node are supported/required.

**Comment by MarshallOfSound** [comment]
This is a known issue with node.js. I'm on my phone at the moment but someone has already raised this upstream with them.

The error is something like EINVAL
