### ISSUE TITLE
Npm ERR! Failed at the electron@1.4.6 postinstall script ‘node install.js’

### ISSUE THREAD

**Issue by laserbeak** [electron/electron-quick-start#105]
Hello,
I've tried electron for the first time last night and am getting errors.
I updated to the latest version of node.js and npm and still got errors. 
I deleted my "electron-quick-start" directory and tried again, using npm install --loglevel verbose and got the attached log.
[npm-debug.log.txt](https://github.com/electron/electron-quick-start/files/588232/npm-debug.log.txt)

 The error is listed below:

> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--loglevel" "verbose"
> npm ERR! node v7.1.0
> npm ERR! npm v3.10.9
> npm ERR! code ELIFECYCLE
> 
> npm ERR! electron@1.4.6 postinstall: node install.js
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the electron@1.4.6 postinstall script 'node install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! node install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR! npm bugs electron
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR! npm owner ls electron
> npm ERR! There is likely additional logging output above.
> npm verb exit [ 1, true ]
> 
> npm ERR! Please include the following file with any support request:
> npm ERR! J:\electron\electron-quick-start\npm-debug.log

**Comment by MarshallOfSound** [comment]
Node 7.1 has issues installing Electron amongst other issues with other packages.

https://github.com/nodejs/node/issues/9542
https://github.com/electron/electron/issues/7919

Downgrade to `7.0.0` or use LTS 👍

**Comment by laserbeak** [comment]
Was using Nodejs 7. Downgraded to version 6 and everything works so far.
