### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by johnking** [electron/electron-quick-start#107]
I played electron long time ago and it worked very well. But I had the issue today - 2016 Nov 19!

I simply cloned this repository and `npm install && npm run start`, but I got errors:
```
app.on('ready', createWindow)
   ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/johnking/workshop/electron/electron-quick-start/main.js:40:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
...
```

I am using the latest electron version: electron@1.4.7

I googled the solutions and tried all kinds of workarounds but could not figure it out.

thanks for any suggestions and help 

-John

**Comment by MarshallOfSound** [comment]
Sounds like your `node_modules` got a bit funky.  Try just deleting your node_modules folder and reinstalling with `npm install`

**Comment by johnking** [comment]
thanks @MarshallOfSound 

I googled the solutions and tried all kinds of workarounds but could not figure it out.

1. I tried to delete and reinstall the electron folder under node_modules
1. I tried to remove the globally installed electron module
1. I tried to delete the whole node_modules and reinstall
1. I also tried logs:
```
console.log(require.resolve('electron'))
console.log(require('electron'))
```
but it did not give me much useful information.
```
/Users/johnking/workshop/electron/electron-quick-start/node_modules/electron/index.js

/Users/johnking/workshop/electron/electron-quick-start/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron
```

it blocks me now ...

**Comment by zeke** [comment]
Just to be sure you're getting a fresh start, please try running these exact commands from scratch, and paste the output here:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

**Comment by johnking** [comment]
Hi Zeke @zeke 

I got the same error after re-doing the steps as you specified. 
```
$ npm start

> electron-quick-start@1.0.0 start /Users/johnking/workshop/electron-quick-start
> electron .

/Users/johnking/workshop/electron-quick-start/main.js:40
app.on('ready', createWindow)
   ^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/Users/johnking/workshop/electron-quick-start/main.js:40:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:402:7)
    at startup (bootstrap_node.js:157:9)
    at bootstrap_node.js:521:3

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/johnking/workshop/electron-quick-start/npm-debug.log
```

I found the information below from electron official site
-----
When using Electron’s built-in module you might encounter an error like this:

```
> require('electron').webFrame.setZoomFactor(1.0)
Uncaught TypeError: Cannot read property 'setZoomLevel' of undefined
```
This is because you have the npm electron module installed either locally or globally, which overrides Electron’s built-in module.

To verify whether you are using the correct built-in module, you can print the path of the electron module:

```
console.log(require.resolve('electron'))
```
and then check if it is in the following form:
```
"/path/to/Electron.app/Contents/Resources/atom.asar/renderer/api/lib/exports/electron.js"
```
If it is something like `node_modules/electron/index.js`, then you have to either remove the npm electron module, or rename it.

```
npm uninstall electron
npm uninstall -g electron
```
---

_I am confused here_, if I uninstall the electron module, the compiler will complain `sh: electron: command not found`. 

thanks a lot for your help.

-John

**Comment by johnking** [comment]
I spent the whole day to find the culprit  .....

It happens when I start the application from ATOM-terminal !!!

**Comment by tylerericmanning** [comment]
@johnking Is there any fix to this?

**Comment by gomonkey** [comment]
it is happen to me the same with atom and normal terminal.
It is one week I try to understand why and what I have to do for resolve it, but still nothing.

I 'm use ubuntu, I installed with super admin privileges and --unsafe-perm=true, this is the unique way for not have any errors.

I removed, I reinstalled, I used global and not global, I try different code, but still not work and I am start to be crazy.

Someone have solution?

**Comment by ZaqTheDuck** [comment]
Using NodeJS command prompt instead of Atom cmd worked for me.

**Comment by emmanuel39hanks** [comment]
replace your scripts with:  
"scripts": {
    "test": "electron .",
    "start": "electron ."
  }

**Comment by suresh1271** [comment]
@emmanuel39hanks Thanks man.. I was facing the issue. With your solution it is working fine.

**Comment by TehcJS** [comment]
Wow @emmanuel39hanks that worked somehow! Thank you so much. I've been debugging for hours trying to find the cause, but couldn't find it until I saw your post.

**Comment by skyyangyun** [comment]
@ emmanuel39hanks useful
