### ISSUE TITLE
npm start failing out of the box on Windows 10 (using Ubuntu bash)

### ISSUE THREAD

**Issue by cassidoo** [electron/electron-quick-start#109]
Initially had some issues with npm and had to install `libasound2`, `libnss3-dev`, `libgconf-2-4`, `libxss1`, and `libxtst6`.  Finally stopped getting npm errors but then got this and I'm stuck!

```
/electron-quick-start$ npm start

> electron-quick-start@1.0.0 start .../electron-quick-start
> electron .

[1117:1121/213915:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument
#0 0x000001e5468e <unknown>
#1 0x000001e6a38b <unknown>
#2 0x000001e6a94d <unknown>
#3 0x00000292cea2 <unknown>
#4 0x0000026f5d75 <unknown>
#5 0x0000026fc0df <unknown>
#6 0x0000026f5506 <unknown>
#7 0x00000121e5b7 <unknown>
#8 0x00000121d090 <unknown>
#9 0x000003475763 main
#10 0x7f43248a1ec5 __libc_start_main
#11 0x000000575dc9 <unknown>
```

Any advice?

**Comment by codebytere** [comment]
hi cassidy! late af followup on this one, apologies...does this happen on the latest `master`? I just PR'd in an update to `2.0.0` which i think might resolve this problem 😁

**Comment by codebytere** [comment]
Closing due to staleness but happy to re-open should more information come to light!

**Comment by PrestonII** [comment]
I guess 2 years is the general response time on this thread :-D  - just getting this error for the first time now.

Running **Ubuntu 20.04 via Windows 10 (WSL)** - let me know if you need any specific specs on the rig though.

Steps:

- cloned down the repo to my drive
- usually, I run `yarn` but I noticed the `package-lock.json` had been commited so I ran `npm i` instead - everything seemed to install normally
- ran `npm start`
- it failed out of the box and gave up a message about missing `libnss3.so` something I've seen with other electron distributions. Here's the longer error message for completion-sake:


```
> electron-quick-start@1.0.0 start /home/maker/_work/elec
> electron .

/home/maker/_work/elec/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
npm ERR! code ELIFECYCLEnpm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! electron-quick-start@1.0.0 start: `electron .`npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maker/.npm/_logs/2020-09-28T20_25_28_859Z-debug.log
```

**Comment by PrestonII** [comment]
Just finding this, which may be related: https://github.com/electron-userland/electron-prebuilt/issues/260
