### ISSUE TITLE
electron start issues

### ISSUE THREAD

**Issue by vennilapanneer** [electron/electron-quick-start#115]
D:\projects\electron-quick-start-master\electron-quick-start-master>npm start

electron-quick-start@1.0.0 start D:\projects\electron-quick-start-master\elect
ron-quick-start-master
electron main.js
module.js:457
throw err;
^

Error: Cannot find module 'D:\projects\electron-quick-start-master\electron-quic
k-start-master\node_modules\electron\cli.js'
at Function.Module._resolveFilename (module.js:455:15)
at Function.Module._load (module.js:403:25)
at Module.runMain (module.js:590:10)
at run (bootstrap_node.js:394:7)
at startup (bootstrap_node.js:149:9)
at bootstrap_node.js:509:3

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v6.7.0
npm ERR! npm v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: electron main.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js
'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start
package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! D:\projects\electron-quick-start-master\electron-quick-start-master
\npm-debug.log

[npm-debug.txt](https://github.com/electron/electron-quick-start/files/624710/npm-debug.txt)

**Comment by fghhfg** [comment]
same here:
```
λ npm start

> electron-quick-start@1.0.0 start C:\Users\user\a6\electron-quick-start
> electron .

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\user\a6\electron-quick-start\node_modules\electron\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (C:\Users\user\a6\electron-quick-start\node_modules\electron\index.js:4:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\a6\electron-quick-start\npm-debug.log
user@user-PC /C/Users/user/a6/electron-quick-start (master)
λ
```

**Comment by MarshallOfSound** [comment]
As mentioned in other issues you probably have a slightly screwed up `node_modules` install.  Just wipe out your `node_modules` directory and try again.  Also ensure you are using your OS's terminal / command prompt as some virtual command lines have some issues launching Electron.
