### ISSUE TITLE
error while start electron

### ISSUE THREAD

**Issue by vennilapanneer** [electron/electron-quick-start#117]
is4800@IS-S1475 MINGW64 /d/projects/electron-quick-start-master/electron-quick-start-master
$ npm start

electron-quick-start@1.0.0 start D:\projects\electron-quick-start-master\electron-quick-start-master
electron main.js
fs.js:549
return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
^

Error: ENOENT: no such file or directory, open 'D:\projects\electron-quick-start-master\electron-quick-start-master\node_modules\electron-prebuilt\path.txt'
at Error (native)
at Object.fs.openSync (fs.js:549:18)
at Object.fs.readFileSync (fs.js:397:15)
at Object. (D:\projects\electron-quick-start-master\electron-quick-start-master\node_modules\electron-prebuilt\index.js:4:42)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.4.7
npm ERR! npm v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: electron main.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! This is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR! npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! D:\projects\electron-quick-start-master\electron-quick-start-master\npm-debug.log

**Comment by BransonGitomeh** [comment]
i got this today, fresh clone

**Comment by aperson111** [comment]
I got this last week, my solution is: 
1. install electron global with command: npm install electron -g
2.cd my electron-quick-start direction to install application: npm install
3. start application:  npm start

**Comment by talhakabakus** [comment]
Got the error pasted below while starting the **quick-start** app on **Ubuntu 14.04**:

```
> electron-quick-start@1.0.0 start /home/talha/git/electron-quick-start
> electron .

sh: 1: electron: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by MarshallOfSound** [comment]
@talhakabakus 

> npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

Did you try upgrading your node version?

**Comment by talhakabakus** [comment]
@MarshallOfSound Just installed the dependencies including **nodejs**; the version of **nodejs** is **v0.10.25**.

**Comment by MarshallOfSound** [comment]
> the version of nodejs is v0.10.25.

That version is very old, (as that log indicates).  Installing node.js from the system sources on Ubuntu fetches a really out of date version.  You want at least `v4.x` and probably `v6.x`.

**Comment by talhakabakus** [comment]
@MarshallOfSound  just upgraded nodejs to `v6.9.2`, still getting error while starting the app:

```
> electron-quick-start@1.0.0 start /home/talha/git/electron-quick-start
> electron .

sh: 1: electron: not found

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/talha/git/electron-quick-start/npm-debug.log
```

**Comment by MarshallOfSound** [comment]
@talhakabakus Now that you have upgraded node versions you probably want to wipe out your `node_modules` directory and re-run the install.

**Comment by talhakabakus** [comment]
Thanks @MarshallOfSound for all your help, now it works as it is expected.

**Comment by codebytere** [comment]
Closing as solution was determined.

**Comment by emptybox** [comment]
> I got this last week, my solution is:
> 
> 1. install electron global with command: npm install electron -g
> 2. cd my electron-quick-start direction to install application: npm install
> 3. start application:  npm start

This worked for me as well. (MacOS/Mojave/10.14.5) (node v8.9.1)

**Comment by Rademenes16** [comment]
same shit
![image](https://user-images.githubusercontent.com/60035016/109966218-46fe5380-7cf0-11eb-99b0-19f23c4ae02e.png)
its fresh install
1000 people collaborated on electron and bugs like this one still happen? Wtf is wrong with this company?

**Comment by herrjemand** [comment]
@Rademenes16 no need to be so toxic
