### ISSUE TITLE
error while loading shared libraries: libnode.so

### ISSUE THREAD

**Issue by nsisodiya** [electron/electron-quick-start#118]
> electron-quick-start@1.0.0 start /home/chip/code/electron-quick-start
> electron .

/home/chip/code/electron-quick-start/node_modules/electron/dist/electron: error while loading shared libraries: libnode.so: cannot open shared object file: No such file or directory

npm ERR! Linux 4.4.13-ntc-mlc
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! spawn ENOENT

=====================

May somebody help me.
I am trying to run electron on ARM based device.

Let me know if you want to know more about system configuration like what kind of processor or what kind of arch I am trying to build.

**Comment by nsisodiya** [comment]
```
uname -a
Linux chip 4.4.13-ntc-mlc #1 SMP Thu Nov 3 01:28:54 UTC 2016 armv7l GNU/Linux
```

**Comment by nsisodiya** [comment]
Somehow, my error gone. I will report here about my findings.

**Comment by niksmac** [comment]
@nsisodiya have you found any reason for the issue.

**Comment by codebytere** [comment]
Given that this appears to be resolved i'm going to go ahead and close this. Please feel free to @ me with any followup issues!
