### ISSUE TITLE
electron installation Code 1

### ISSUE THREAD

**Issue by ibrido90** [electron/electron-quick-start#120]
Hello I am just trying to install electron on my pc. After it crashes (see screenshot)

![electron_error_install](https://cloud.githubusercontent.com/assets/2493217/21450617/f2f6b02a-c8f8-11e6-9af5-8fae2876aa4a.png)

This happens both cloning the quickstart and running `npm install` and running `npm install electron`.
I also tried to do this with admin privileges, but still the same.
Any hint?

**Current operating system**: Windows 10

**Comment by ibrido90** [comment]
Solved downgrading node.js to LTS version

**Comment by zeke** [comment]
Thanks for following up, @ibrido90
