### ISSUE TITLE
"electron ." fails on system.

### ISSUE THREAD

**Issue by mcncl** [electron/electron-quick-start#122]
> electron-quick-start@1.0.0 start /Users/benmcnicholl/electron-quick-start
> electron .
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT: no such file or directory, open '/Users/benmcnicholl/electron-quick-start/node_modules/electron/path.txt'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at Object.<anonymous> (/Users/benmcnicholl/electron-quick-start/node_modules/electron/index.js:4:42)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/benmcnicholl/electron-quick-start/npm-debug.log`

**Comment by MarshallOfSound** [comment]
> Error: ENOENT: no such file or directory, open '/Users/benmcnicholl/electron-quick-start/node_modules/electron/path.txt'

This normally means that your `node_modules` install went wrong somewhere.  Try deleting the `node_modules/electron` folder and rerunning `npm install`
