### ISSUE TITLE
 invalid WIN32 path characters

### ISSUE THREAD

**Issue by anandfingertip** [electron/electron-quick-start#123]
Error: C:\Users\Anand\AppData\Local\Temp;C:\Work\apache-maven-3.2.5-bin\apache-maven-3.2.5\bin;C:\Program Files\Java\jdk1.8.0_31\bin;.;\electron-tmp-download-14672-1483024596459 contains invalid WIN32 path characters.
    at Object.mkdirs (c:\Work\Desktop-App\electron-quick-start\node_modules\fs-extra\lib\mkdirs\mkdirs.js:16:20)
    at ElectronDownloader.createTempDir (c:\Work\Desktop-App\electron-quick-start\node_modules\electron-download\build\index.js:104:10)
    at c:\Work\Desktop-App\electron-quick-start\node_modules\electron-download\build\index.js:158:16
    at c:\Work\Desktop-App\electron-quick-start\node_modules\electron-download\build\index.js:97:9
    at c:\Work\Desktop-App\electron-quick-start\node_modules\fs-extra\lib\mkdirs\mkdirs.js:54:16
    at c:\Work\Desktop-App\electron-quick-start\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:111:15)
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Work\Desktop-App\electron-quick-start\npm-debug.log

**Comment by codebytere** [comment]
Please try to `npm i && electron .` with the most recent version of `electron-quick-start`

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in https://github.com/electron/electron-quick-start/issues/123#issuecomment-361798808. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
