### ISSUE TITLE
Failed to start electron quick start

### ISSUE THREAD

**Issue by saeedhbi** [electron/electron-quick-start#126]
Hi,

I'm using windows 10 + vagrant environment and try to run electron-quick-start but there is problem with that. Here is my error:

 ```
> electron-quick-start@1.0.0 start /home/vagrant/Code/projects/electron-quick-start
> electron .


npm ERR! Linux 3.13.0-93-generic
npm ERR! argv "/home/vagrant/.nvm/versions/node/v6.9.4/bin/node" "/home/vagrant/.nvm/versions/node/v6.9.4/bin/npm" "start"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
```

I do this with and without root access and get error on both of them. How can I fix it? Here is my environment information:

* Windows 10 + Vagrant 1.8.5
* Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-93-generic x86_64)
* Node v6.9.4
* Npm v4.1.2

**Comment by MarshallOfSound** [comment]
You are trying to launch Electron (a GUI application) from a headless server style Linux environment.  There's no screen for it to attach to so it will fail.

If you want to Dev on Windows use command prompt / tools actually in Windows.  If you want to Dev on Linux use a full desktop VM like Ubuntu Desktop in virtual box

**Comment by saeedhbi** [comment]
Thank you. My mistake.
