### ISSUE TITLE
error npm install 

### ISSUE THREAD

**Issue by gearcapitan** [electron/electron-quick-start#145]
![kali linux-2017-04-13-17-52-34](https://cloud.githubusercontent.com/assets/13740942/25027407/0f87edf0-2072-11e7-9a47-4d1f60a5f852.png)

**Comment by MarshallOfSound** [comment]
Please update your `node` and `npm` versions to be more recent.  Ideally you would have node 6.X and npm 3.X

**Comment by Ashlanfox** [comment]
I think you need to install nodejs legacy: 

> sudo apt-get install nodejs-legacy

**Comment by gearcapitan** [comment]
─➤  apt-get install nodejs-legacy
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
No se pudieron instalar algunos paquetes. Esto puede significar que
usted pidió una situación imposible o, si está usando la distribución
inestable, que algunos paquetes necesarios aún no se han creado o se
han sacado de «Incoming».
La siguiente información puede ayudar a resolver la situación:

Los siguientes paquetes tienen dependencias incumplidas:
 nodejs-legacy : Depende: nodejs (>= 0.6.19~dfsg1-3~) pero no va a instalarse
E: No se pudieron corregir los problemas, usted ha retenido paquetes rotos.

**Comment by zeke** [comment]
@MarshallOfSound's recommendation is *ahem* sound:

> Please update your node and npm versions to be more recent. Ideally you would have node 6.X and npm 3.X
