### ISSUE TITLE
ES6 De-structuring

### ISSUE THREAD

**Issue by Hum4n01d** [electron/electron-quick-start#146]
Is there a reason that the imports in the quickstart aren’t being destructured like this:

```
const {app, BrowserWindow} = require('electron')
```

I’d make a PR but I’m wondering if it’s to support older versions of node, simpler code, etc.

**Comment by MarshallOfSound** [comment]
See #71 

> I’d like to not discuss what is “cleaner” but rather what most people will recognize when they read it
> For the purposes of this quickstart repo, familiarity trumps dexterity.
