### ISSUE TITLE
Not work npm install && npm start

### ISSUE THREAD

**Issue by nitsik** [electron/electron-quick-start#147]
Hello. I do

> git clone https://github.com/electron/electron-quick-start
> cd electron-quick-start
> npm install && npm start

And I have errors:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.10.2
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
> 6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
> 8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/electron-quick-start/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/vesta/bin
> 10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /electron-quick-start
> 11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
> 12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
> 13 verbose stack spawn ENOENT
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
> 13 verbose stack     at emitTwo (events.js:106:13)
> 13 verbose stack     at ChildProcess.emit (events.js:191:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:886:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 14 verbose pkgid electron-quick-start@1.0.0
> 15 verbose cwd /electron-quick-start
> 16 error Linux 3.16.0-4-amd64
> 17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 18 error node v6.10.2
> 19 error npm  v3.10.10
> 20 error file sh
> 21 error code ELIFECYCLE
> 22 error errno ENOENT
> 23 error syscall spawn
> 24 error electron-quick-start@1.0.0 start: `electron .`
> 24 error spawn ENOENT
> 25 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
> 25 error Make sure you have the latest version of node.js and npm installed.
> 25 error If you do, this is most likely a problem with the electron-quick-start package,
> 25 error not with npm itself.
> 25 error Tell the author that this fails on your system:
> 25 error     electron .
> 25 error You can get information on how to open an issue for this project with:
> 25 error     npm bugs electron-quick-start
> 25 error Or if that isn't available, you can get their info via:
> 25 error     npm owner ls electron-quick-start
> 25 error There is likely additional logging output above.
> 26 verbose exit [ 1, true ]

How fix it? Thank you.

**Comment by MarshallOfSound** [comment]
@nitsik It looks like your `npm install` failed, can you run

```bash
rm -rf node_modules
npm install
npm start
```

And see how that goes 👍

**Comment by nitsik** [comment]
I try this, but see

> npm start
> 
> > electron-quick-start@1.0.0 start /electron-quick-start
> > electron .
> 
> /electron-quick-start/node_modules/electron/dist/electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
> 
> npm ERR! Linux 3.16.0-4-amd64
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! electron-quick-start@1.0.0 start: `electron .`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     electron .
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs electron-quick-start
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls electron-quick-start
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /electron-quick-start/npm-debug.log

npm-debug.log:

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
> 2 info using npm@3.10.10
> 3 info using node@v6.10.2
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
> 6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
> 7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
> 8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
> 9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/electron-quick-start/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/vesta/bin
> 10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /electron-quick-start
> 11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
> 12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
> 13 verbose stack spawn ENOENT
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
> 13 verbose stack     at emitTwo (events.js:106:13)
> 13 verbose stack     at ChildProcess.emit (events.js:191:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:886:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
> 14 verbose pkgid electron-quick-start@1.0.0
> 15 verbose cwd /electron-quick-start
> 16 error Linux 3.16.0-4-amd64
> 17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
> 18 error node v6.10.2
> 19 error npm  v3.10.10
> 20 error file sh
> 21 error code ELIFECYCLE
> 22 error errno ENOENT
> 23 error syscall spawn
> 24 error electron-quick-start@1.0.0 start: `electron .`
> 24 error spawn ENOENT
> 25 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
> 25 error Make sure you have the latest version of node.js and npm installed.
> 25 error If you do, this is most likely a problem with the electron-quick-start package,
> 25 error not with npm itself.
> 25 error Tell the author that this fails on your system:
> 25 error     electron .
> 25 error You can get information on how to open an issue for this project with:
> 25 error     npm bugs electron-quick-start
> 25 error Or if that isn't available, you can get their info via:
> 25 error     npm owner ls electron-quick-start
> 25 error There is likely additional logging output above.
> 26 verbose exit [ 1, true ]
>

**Comment by nerososft** [comment]
@nitsik same question ,no debug log

**Comment by zeke** [comment]
@nitsik I think your answer is here: https://github.com/electron/electron/issues/1518#issuecomment-97199038
