### ISSUE TITLE
npm install not work

### ISSUE THREAD

**Issue by nerososft** [electron/electron-quick-start#148]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/neroyang/project/front/electron-quick-start/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /Users/neroyang/project/front/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:885:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /Users/neroyang/project/front/electron-quick-start
16 error Darwin 16.5.0
17 error argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "start"
18 error node v7.4.0
19 error npm  v4.0.5
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error electron-quick-start@1.0.0 start: `electron .`
24 error spawn ENOENT
25 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the electron-quick-start package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs electron-quick-start
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls electron-quick-start
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by nerososft** [comment]
[screenshot](https://d2ppvlu71ri8gs.cloudfront.net/items/1d3D0L0S3Y3d2U1l332q/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202017-04-27%20%E4%B8%8A%E5%8D%881.09.22.png?v=32dd5b18)

**Comment by nerososft** [comment]
![](https://d2ppvlu71ri8gs.cloudfront.net/items/1d3D0L0S3Y3d2U1l332q/屏幕快照%202017-04-27%20上午1.09.22.png "screenshot")

**Comment by trescube** [comment]
The problem is that electron is listed in `devDependencies` so if you ran `npm install --production` or have an environmental variable named `NODE_ENV` set to `production` then the electron dependency won't be installed in `node_modules`.

**Comment by zeke** [comment]
It looks your installation failed. This should do the trick:

```sh
rm -rf node_modules
npm install
npm start
```
