### ISSUE TITLE
npm start Error

### ISSUE THREAD

**Issue by bibin14** [electron/electron-quick-start#149]
C:\Users\bibin_000\Documents\GitHub\electron-quick-start>npm start

> electron-quick-start@1.0.0 start C:\Users\bibin_000\Documents\GitHub\electron-quick-start
> electron .

module.js:457
    throw err;
    ^

Error: Cannot find module 'C:\Users\bibin_000\Documents\GitHub\electron-quick-start\node_modules\electron\cli.js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bibin_000\Documents\GitHub\electron-quick-start\npm-debug.log

**Comment by zeke** [comment]
It looks your installation failed. This should do the trick:

```sh
rm -rf node_modules
npm install
npm start
```
