### ISSUE TITLE
menu is missing on mac

### ISSUE THREAD

**Issue by feifeipan** [electron/electron-quick-start#151]
I run the start demo on mac, everything is ok except the menu is missing.

Can someone help me?Thanks

<img width="1064" alt="2017-05-03 10 28 14" src="https://cloud.githubusercontent.com/assets/2155605/25646698/7b666968-2fed-11e7-88f8-24240eae86d3.png">

**Comment by zeke** [comment]
That is strange. Do you see any errors in your terminal or in the browser window's console?

<img width="274" alt="screen shot 2017-06-12 at 3 52 13 pm" src="https://user-images.githubusercontent.com/2289/27058613-2df6b12e-4f87-11e7-889c-71c7e12d54d0.png">
