### ISSUE TITLE
Electron.exe detected as Virus from Avast

### ISSUE THREAD

**Issue by Kryze** [electron/electron-quick-start#154]
Hey,
When i try to run the quick-start app, i got alert from Avast who block my Electron.exe
Is it a false positive ?
Thanks 

![image](https://user-images.githubusercontent.com/18222418/26866116-0db1c7e4-4b60-11e7-829f-01b8266d2036.png)

**Comment by rohan-ramesh** [comment]
This isn't an issue with the Electron quick start, but rather Electron itself. You probably won't find an answer here. For issues with electron, go [here](https://github.com/electron/electron).

**Comment by MarshallOfSound** [comment]
@Kryze @rohan-ramesh This is a false positive, plain and simple 😄 You should report it as such to your antivirus provider 👍
