### ISSUE TITLE
Electronjs

### ISSUE THREAD

**Issue by pavankamath1406** [electron/electron-quick-start#162]
> pavan@1.0.0 start C:\Electron_js
> electron index.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pavan@1.0.0 start: `electron index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pavan@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
 
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\General\AppData\Roaming\npm-cache\_logs\2017-07-28T04_00_56_603Z-debug.log

 I am getting these error while running     npm start

**Comment by zeke** [comment]
Please share the contents of index.js and the debug log.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in https://github.com/electron/electron-quick-start/issues/162#issuecomment-318802866. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
