### ISSUE TITLE
npm start script fails

### ISSUE THREAD

**Issue by kamenjan** [electron/electron-quick-start#166]
I am having some difficulties starting this application. Start script fails and throws error with following trace back:

```
$ npm start

> electron@1.7.6 start /Users/rok/Projects/Crypto/electron-quick-start/electron
> python ./script/start.py

Traceback (most recent call last):
  File "./script/start.py", line 43, in <module>
    sys.exit(main())
  File "./script/start.py", line 37, in main
    subprocess.check_call([electron] + sys.argv[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.6 start: `python ./script/start.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.7.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rok/.npm/_logs/2017-08-17T21_12_35_391Z-debug.log
```
I'm running this on macOS - Sierra, npm 5.3.0, node v.8.4.0 and Python 2.7.10.

After some research I found out it might have to do something with python being unable to navigate around the file system, but I don't know much python. Any idea?

**Comment by nicolehli** [comment]
Hi @kamenjan , try adding python to your computer environment path https://www.techwalla.com/articles/how-to-set-your-python-path

**Comment by zeke** [comment]
You shouldn't have to install python.

Can you outline the steps that got you to this error?

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in https://github.com/electron/electron-quick-start/issues/166#issuecomment-335269987. With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
