### ISSUE TITLE
Cannot debug electron-quick-start in VSCode

### ISSUE THREAD

**Issue by MbProg** [electron/electron-quick-start#170]
Hello, I am able to run this code with cmd in Windows 8 and also with the integrated cmd in VS Code. But it fails when I try to debug the code. I get the following bug:

> Debugger listening on [::]:46522
> e:\Projects\BT\electron-quick-start\main.js:40
> app.on('ready', createWindow)
>    ^
> 
> TypeError: Cannot read property 'on' of undefined
>     at Object.<anonymous> (e:\Projects\BT\electron-quick-start\main.js:40:4)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
>     at Function.Module._load (module.js:438:3)
>     at Timeout.Module.runMain [as _onTimeout] (module.js:604:10)
>     at ontimeout (timers.js:365:14)
>     at tryOnTimeout (timers.js:237:5)
>     at Timer.listOnTimeout (timers.js:207:5)
This happens when the debugger reaches the following line:
>     app.on('ready', createWindow)
 
I am using exactly the code and have used exactly the instruction declare here. So it is working the cmd terminal. But I don't know why it fails debugging with VS Code?

**Comment by haschdl** [comment]
Same problem here, except that I'm using Windows 10.

**Comment by haschdl** [comment]
@MbProg  I just upgraded VS Code and debugging is working fine. Maybe it's now working for you as well?

**Comment by MbProg** [comment]
@haschdl  Yes thanks. The new update fixed it. It works for me too.

**Comment by MbProg** [comment]
Now a new update of VS Code came out which destroyed everything. Now again debugging is not possible. It is a disaster

**Comment by WeiZhang418** [comment]
The update of VS Code，1.25.1， still can't debug for electron

**Comment by maduhaime** [comment]
Same with Version 1.28.2 (1.28.2) on MacOS Mojave.

**Comment by Ramesh9590** [comment]
I have updated with 1.29.1 but still i am facing the issue.

**Comment by rKinson** [comment]
Same Issue

Version: 1.32.3 (system setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
