### ISSUE TITLE
Visualizing data flow

### ISSUE THREAD

**Issue by MbProg** [electron/electron-quick-start#178]
Hello, I don't know if here is the correct place here. I want to visualize data flow in Electron. I want to draw a graph and show data flowing between some nodes of the graph on the edges. This data flow should animate between the source node to the destination node. 
Does anyone know an open source component doing that in Electron?

**Comment by yoat** [comment]
This is not the correct place for that question.  Check D3.js for HTML/JS/CSS graph visualizations, and ask specific implementation questions on StackOverflow.com.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
