### ISSUE TITLE
npm start does not launch app reliably under Win10 "cmd" shell

### ISSUE THREAD

**Issue by oparisy** [electron/electron-quick-start#181]
I am running electron-quick-start on an up-to-date Windows 10, from the `cmd` shell.

The first time I run `npm start`, the quick start application starts (I can see the Electron process in Process Explorer, and its "Hello World" window appear).

But once this application is properly exited, most `npm start` will not yield the "Hello World" windows. The shell will be stuck on `> electron .`, nothing appears and I get Electron process in Process Explorer.

It seems like relentlessly launching new `cmd` shells sometimes helps in getting the process starting, but this is not reliable.

Is using the `cmd` shell supported? How can I help in investigating this?

**Comment by oparisy** [comment]
Interestingly, manually launching `electron.exe` from `cmd` (using the absolute path to `\electron-quick-start\node_modules\electron\dist\electron.exe`) will exhibit the same behavior (the default Electron window rarely appear).

Actually, even clicking on `electron.exe` using Windows 10 Explorer rarely launch it, so I am kind of lost as to what the proper behavior should be.

**Comment by oparisy** [comment]
OK, this is clearly related to https://github.com/electron-userland/electron-prebuilt-compile/issues/36.

I am using an Acer computer; killing `ePowerEvent` ensures I can reliably launch `electron-quick-start` in the above scenario.

Since a workaround exists and is not related to this code base, I'm closing this issue.

**Comment by spennywallstest** [comment]
how do you kill ePowerEvent.exe!?
