### ISSUE TITLE
Fail to run

### ISSUE THREAD

**Issue by olproff** [electron/electron-quick-start#185]
Hello everybody,
I have installed for the first time and than run by using instructions bellow, but i having the next errors:
GNU nano 2.5.3                                                    File: /home/olproff/devel/electron-quick-start/npm-debug.log                                                                                                              

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/olproff/devel/electron-quick-start/node_modules/.bin:/home/olproff/bin:/home/olproff/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u$
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/olproff/devel/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /home/olproff/devel/electron-quick-start
16 error Linux 4.10.0-38-generic
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error electron-quick-start@1.0.0 start: `electron .`
24 error spawn ENOENT
25 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the electron-quick-start package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs electron-quick-start
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls electron-quick-start
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by codebytere** [comment]
try running 
```
$ npm i -g electron
$ npm start
```

**Comment by mobi12** [comment]
Why loadFile() is not a function?

**Comment by codebytere** [comment]
We haven't received follow-up to the advice posted above, and so i'm going to go ahead and close this. Happy to re-open should more information come to light!
