### ISSUE TITLE
Change .js extension to .ts

### ISSUE THREAD

**Issue by emerico** [electron/electron-quick-start#190]
Yes we still use .js extension but in some intelligent editors like webstrom it shows too many errors because it didn't recognized typescript syntax in .js extension, and i believe almost every editor have support to typescript so we must need to change .js extension to .ts

**Comment by vanessayuenn** [comment]
@emerico if you'd like to use typescript with the quick start project, https://github.com/electron/electron-quick-start-typescript would be what you're looking for instead. It's basically the same quick start project in this repo, but written with Typescript.
