### ISSUE TITLE
Running the EXE， taskbar has three processes

### ISSUE THREAD

**Issue by 18037999752** [electron/electron-quick-start#196]
Start with “npm start”，there has three processes in taskbar.This is why?
![image](https://user-images.githubusercontent.com/33300933/38235391-9dfe5972-3753-11e8-8ba7-f149048b40ec.png)

**Comment by MarshallOfSound** [comment]
They are:

* Main process
* Renderer process
* GPU process

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
