### ISSUE TITLE
transparent bug

### ISSUE THREAD

**Issue by guoyangMr** [electron/electron-quick-start#200]
Hi, I hope you can see and fix the bug, we are based on the development of electron Mac desktop applications, found a problem: if you use a transparent window (transparent: true), when frequently updated dom, if the window loses focus, can appear the remaining text shadows.

**Comment by codebytere** [comment]
Hi! Thanks for reporting this, but this is an issue best opened on `electron/electron` [here](https://github.com/electron/electron/issues/new/choose). 

In the meantime i'm going to close this.
