### ISSUE TITLE
npn start error(using git bash in win10 64bit)

### ISSUE THREAD

**Issue by JINxo-geek** [electron/electron-quick-start#202]
$ npm start

> electron-quick-start@1.0.0 start C:\Users\Administrator\OneDrive\ElectronDemo\electron-quick-start
> electron .

fs.js:1669
      binding.lstat(baseLong);
              ^

Error: EINVAL: invalid argument, lstat 'C:\Users\Administrator\OneDrive'
    at realpathSync (fs.js:1669:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:330:24)
    at toRealPath (module.js:143:13)
    at Function.Module._findPath (module.js:192:22)
    at Function.Module._resolveFilename (module.js:483:25)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-04-30T07_15_03_113Z-debug.log

**Comment by JINxo-geek** [comment]
How to reproduce

Just run any electron project with electron path from a directory path containing non-ASCII characters.

I remove my project to disk root directory,the problem was fixed

**Comment by codebytere** [comment]
This is an issue present on `electron/electron` here: https://github.com/electron/electron/issues/12725

I'm going to close this and you can follow that issue for updates.
