### ISSUE TITLE
npm run dev ERR!  How to solve problems?

### ISSUE THREAD

**Issue by eric9991517** [electron/electron-quick-start#211]
npm run dev ERR!  How to solve problems?

this is my ERR message:

`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! imps@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the imps@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yiyi.chen\AppData\Roaming\npm-cache\_logs\2018-05-31T03_12_03_379Z-debug.log`

This is debug.log message:

`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\yiyi.chen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@6.1.0
3 info using node@v10.1.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle imps@1.0.0~predev: imps@1.0.0
6 info lifecycle imps@1.0.0~dev: imps@1.0.0
7 verbose lifecycle imps@1.0.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle imps@1.0.0~dev: PATH: C:\Users\yiyi.chen\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Project1\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseSVN\bin;C:\Users\yiyi.chen\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\nodejs\;C:\Users\yiyi.chen\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\yiyi.chen\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\yiyi.chen\AppData\Roaming\npm
9 verbose lifecycle imps@1.0.0~dev: CWD: D:\Project1
10 silly lifecycle imps@1.0.0~dev: Args: [ '/d /s /c',
10 silly lifecycle   'webpack-dev-server --inline --progress --config build/webpack.dev.conf.js' ]
11 silly lifecycle imps@1.0.0~dev: Returned: code: 1  signal: null
12 info lifecycle imps@1.0.0~dev: Failed to exec dev script
13 verbose stack Error: imps@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\yiyi.chen\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\yiyi.chen\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:957:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
14 verbose pkgid imps@1.0.0
15 verbose cwd D:\Project1
16 verbose Windows_NT 10.0.16299
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yiyi.chen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v10.1.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error imps@1.0.0 dev: `webpack-dev-server --inline --progress --config build/webpack.dev.conf.js`
22 error Exit status 1
23 error Failed at the imps@1.0.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by codebytere** [comment]
Hi @eric9991517, this is an issue with webpack and not with electron, please open an issue there for more help!
