### ISSUE TITLE
app icon in quick start(newbie)

### ISSUE THREAD

**Issue by lohriialo** [electron/electron-quick-start#218]
I just got introduced to electron today and I think I'm liking it so far. Running the quick start example but I have a question, where is the app icon coming from? I don't see it defined anywhere in the `.js/.json/.html`

**Comment by shiftkey** [comment]
@lohriialo please have a read of [this StackOverflow answer](https://stackoverflow.com/a/31538436/1363815) to see how to change it (there's some platform differences).

The default icon you're seeing is the Electron icon, which is displayed if you don't have an icon configured.
