### ISSUE TITLE
Question: is a global window object necessary?

### ISSUE THREAD

**Issue by jerry1100** [electron/electron-quick-start#221]
In main.js:
```javascript
// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow
```

My question: even if `mainWindow` was locally-scoped, wouldn't the reference in the `mainWindow.on('closed')` event handler prevent it from being garbaged collected? Specifically, [this](https://github.com/electron/electron-quick-start/blob/master/main.js#L23).

**Comment by MarshallOfSound** [comment]
@jerry1100 Although that event handler may prevent it from being GC'ed we added that commend and made the variable global scoped to explain a common "gotcha" when people are writing Electron apps.

**Comment by jhg** [comment]
Excuse me to ask here, but it's related and maybe it's better than open new issue when it's related even it's a different question.

If `BrowserWindow.getAllWindows()` https://electronjs.org/docs/api/browser-window#browserwindowgetallwindows get an array with all windows, then I guess electron store all windows, then is really necessary we duplicate that feature keeping another array when we're using multi window for GC not close our windows? I mean, if electron manage windows and allow to get all windows, then I guess GC is not a problem.
