### ISSUE TITLE
Shows an empty window

### ISSUE THREAD

**Issue by cstayyab** [electron/electron-quick-start#224]
**OS:** Debian 9
**Environment:** KDE
Shows an empty window. Index.html page is not loading. See the following screenshot. It shows the the new Electron window is just a transparent window.
[https://i.imgur.com/iI1VrLA.png](https://i.imgur.com/iI1VrLA.png)

Trying to figure out problem from last several hours but no luck.

**Comment by ollietb** [comment]
This also happens for me on Raspberry Pi 3

**Comment by vaporwavie** [comment]
Disabling hardware acceleration is helping us out while the proper fix comes in, so thanks @jonatjano!

**Comment by shiftkey** [comment]
The `electron-quick-start` project is just a scaffold for people to get started with an Electron app.

If you're looking for support with troubleshooting a specific OS or setup with Electron please check the main [issue tracker](https://github.com/electron/electron/issues) to see if it's been previously reported.
