### ISSUE TITLE
No Window appears on start

### ISSUE THREAD

**Issue by jlshattuck** [electron/electron-quick-start#238]
When attempting to start electron-quick-start on Windows 10, no window appears.  No errors either.  However, Electron does launch successfully if I create a raw npm init project and add electron (e.g. npm install electron --save-dev, create main.js with basic window code etc.) and uses version 3.0.10.

I run the following commands:
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start

--Info---
Windows 10
$ node --version
v11.1.0

$ npm --version
6.4.1

**Comment by 5urpher** [comment]
I'm having the exact same issue. I was initially trying to start an electron/vue app that I hadn't touched since the 9th Nov.

**Comment by 5urpher** [comment]
Updating Node to v11.3.0 solved my issues.

**Comment by jlshattuck** [comment]
Success. Upgrading to to Node v11.3.0 resolved this issue.  Thanks 5urpher!
