### ISSUE TITLE
TypeError: Cannot set property '_nodeValue' of undefined 

### ISSUE THREAD

**Issue by krishnappahuded** [electron/electron-quick-start#255]
In my application it's throwing different error like
TypeError: Cannot set property '_nodeValue' of undefined TypeError: Cannot set property '_nodeValue' of undefined

If we have any solution please help me.

_Originally posted by @krishnappahuded in https://github.com/electron/electron-quick-start/issues/30#issuecomment-459616580_

**Comment by MarshallOfSound** [comment]
Without a repro this sounds like it's an error coming from your code rather than Electron.  If you can reproduce this standalone in Electron please raise an issue on the Electron repo.
