### ISSUE TITLE
It can not work in China

### ISSUE THREAD

**Issue by zaoqi** [electron/electron-quick-start#260]
```
$ npm install

> electron@4.0.4 postinstall /home/23494_sandbox/src/electron-quick-start/node_modules/electron
> node install.js

Downloading tmp-13579-0-electron-v4.0.4-linux-x64.zip
[==>                                          ] 8.0% of 75.15 MB (25.55 kB/s)
```
Then it stopped

**Comment by sjx233** [comment]
It **can** work. Check your Internet connection.

**Comment by zaoqi** [comment]
> It **can** work. Check your Internet connection.

I waited for a lot of hours and it ended successfully. It does work, as long as I have a lot of time.

**Comment by NieLamu** [comment]
Download electron packages you need from [electron mirror](https://npm.taobao.org/mirrors/electron/), 
 put them in `C:\Users\yourName\.electron` like the screenshot, then run `npm install`.
<img width="262" alt="x" src="https://user-images.githubusercontent.com/35550993/53697972-c4e1a880-3e11-11e9-8812-086311b739dd.PNG">

**Comment by DingFengzuoan** [comment]
npm install takes way too long.Downloading is really slow in China

**Comment by sjx233** [comment]
Solution: `ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/" npm install`.

**Comment by amorist** [comment]
[自定义镜像和缓存](https://electronjs.org/docs/tutorial/installation#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%95%9C%E5%83%8F%E5%92%8C%E7%BC%93%E5%AD%98)

![image](https://user-images.githubusercontent.com/14037268/55299302-00997d80-5465-11e9-8a46-d8a695ffa62e.png)
