### ISSUE TITLE
Cannot use web3 within an electron app

### ISSUE THREAD

**Issue by barakman** [electron/electron-quick-start#269]
Platform:
- Windows 10 64 bits
- node v10.15.3
- npm v6.4.1

File package.json:
```
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "devDependencies": {
    "electron": "^4.1.1",
    "web3": "1.0.0-beta.34"
  }
}
```
File index.html:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
  </head>
  <body>
    <script>
        try {
            web3 = require("web3");
        }
        catch (error) {
            alert(error.message);
        }
    </script>
  </body>
</html>
```
Execution:
```
npm install
npm start
```
Result:
> The module
> '\\?\C:\...scrypt\build\Release\scrypt.node'
> was compiled against a different Node.js version using
> NODE_MODULE_VERSION_64. This version of Node.js requires
> NODE_MODULE_VERSION_69. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`).

**Comment by barakman** [comment]
For different versions of Electron, I get slightly different errors:
- v5.0.0-beta.7 gives the same error, but with `68` instead of `69`
- both v3.1.7 and v2.0.18 give "a dynamic link library (DLL) initialization routine failed.", followed by the full path of `scrypt.node`

**Comment by barakman** [comment]
Workaround:

After `npm install`, open file `/node_modules/web3-eth-accounts/src/index.js` and mask the line:
```
var scryptsy = require('scrypt.js');
```

**Comment by shiftkey** [comment]
@barakman the original error you are seeing is because of a native Node module that is not being built against the version of Node embedded in Electron. The documentation about [Using Native Node Modules](https://electronjs.org/docs/tutorial/using-native-node-modules) shows how you can setup your project to work properly with these modules...

**Comment by barakman** [comment]
@shiftkey :

I've already come across this page, as part of my research on this issue.
I did try some of the suggestions, for example `electron-rebuild`, which did not seem to resolve the problem.

Other suggestions aren't very easy-to-follow, and seem to require quite a few steps to get things right (possibly, and possibly not).

I believe that my problem is under the category of "Windows + node-gyp", which seems to consist of may other (not-necessarily related) problems.

For now, the workaround above is good enough for my needs, since my app doesn't make use of `web3.eth.accounts`.

Thanks :)

**Comment by codebytere** [comment]
Closing as this is not an issue with `electron-quick-start` itself.
