### ISSUE TITLE
Something wrong with my raspberrypi

### ISSUE THREAD

**Issue by yuanyehome** [electron/electron-quick-start#276]
> electron-quick-start@1.0.0 start /home/pi/workplace/test0/electron-quick-start
> electron .

/home/pi/workplace/test0/electron-quick-start/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.27' not found (required by /home/pi/workplace/test0/electron-quick-start/node_modules/electron/dist/electron)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-26T12_16_11_267Z-debug.log

Why did I failed?

**Comment by shiftkey** [comment]
> /home/pi/workplace/test0/electron-quick-start/node_modules/electron/dist/electron: /lib/arm-linux-gnueabihf/libc.so.6: version GLIBC_2.27' not found (required by /home/pi/workplace/test0/electron-quick-start/node_modules/electron/dist/electron)

@yuanyehome please read https://github.com/electron/electron/issues/16205 as that provides some context to the underlying issue with using Electron on Raspberry Pi currently.

**Comment by codebytere** [comment]
Closing given above context.
