### ISSUE TITLE
preload.js Issue: Cannot set property 'innerText' of null

### ISSUE THREAD

**Issue by mrcush** [electron/electron-quick-start#295]
I'm assuming this is a bug (I'm just starting learning Electron), I don't have any issues if I just disable the preload.js script but I saw a commit mentioning that preload.js is more secure than nodeIntegration.  However, dev tools gives me a big squiggly line under
```
= process.versions[versionType]
```
And the error is <code>Uncaught TypeError: Cannot set property 'innerText' of null.

I'm not sure what this is doing but I can't stand big fat red errors in my dev tools so I'm switching over to nodeIntegration for now but I'll check back to see if this is something that gets fixed or to see if I'm somehow at fault >.>

EDIT: And it seems "devtron" will not work without nodeIntegration or this preload script

**Comment by codebytere** [comment]
@mrcush i'm not sure i understand the issue here: is this an issue with this repo out of the box? as in, you see this the very first time you run this?

**Comment by mrcush** [comment]
Gotcha, sounds good.
