### ISSUE TITLE
npm start and empty window

### ISSUE THREAD

**Issue by yeb-skp** [electron/electron-quick-start#310]
Hello, 
I am trying to launch the app by following the example "electron quick start" but it seems to me there is a problem. When I write npm start on my terminal, it creates a window but I cannot see my app. Despite this problem, no errors are writing on my terminal. I would like to know if this problem comes from the start R file and how to fix it.
Best regards,
Yanis

**Comment by yeb-skp** [comment]
PS: I am working on windows.

**Comment by codebytere** [comment]
Unfortunately, this is not enough information for us to proceed. What, precisely, happens in terminal? what version of windows? do you have screenshots? have you modified the stock code in any way?

**Comment by yeb-skp** [comment]
I'm trying to do follow this example https://github.com/ColumbusCollaboratory/electron-quick-start.
I am following the instructions and I'm writing the commands in my terminal (first picture). I have no errors or warnings and when I write "npm start", a window appears but after the loading, the window is just empty (picture 2). I have installed both Nodejs and Git so that's why I don't understand where is the problem. I have not modified any file in the folder electron quick start (picture 3) and I am using Windows 10 with a 64 bit processor. 
Thank you for you help.


![terminal eqs1](https://user-images.githubusercontent.com/54170716/63278784-37532180-c2a8-11e9-85b6-7a4173ef44bf.PNG)
![terminal eqs2](https://user-images.githubusercontent.com/54170716/63278789-39b57b80-c2a8-11e9-8cf3-507e6ea9166b.PNG)
![folder](https://user-images.githubusercontent.com/54170716/63278962-8436f800-c2a8-11e9-8376-589772e7f186.PNG)

**Comment by codebytere** [comment]
Have you checked your devtools console? What do you see there?

**Comment by yeb-skp** [comment]
I'm sorry but I don't know how to see the devtools console and I don't find on the internet. Could you help me ?

**Comment by yeb-skp** [comment]
I do not have Javascript. Could it explain why my app doesn't launch in the window ?

**Comment by yeb-skp** [comment]
I didn't have the devtools because I wasn't administrator. Here is what I get when I write npm start
<img width="943" alt="Capture1" src="https://user-images.githubusercontent.com/54170716/63414936-2962e500-c3fd-11e9-9d3d-787855a56add.png">
<img width="943" alt="Capture2" src="https://user-images.githubusercontent.com/54170716/63414937-2962e500-c3fd-11e9-99bd-45bbfba1794b.png">
<img width="948" alt="Capture3" src="https://user-images.githubusercontent.com/54170716/63414938-2962e500-c3fd-11e9-8fe2-c990545f04de.png">
<img width="941" alt="Capture4" src="https://user-images.githubusercontent.com/54170716/63414939-2962e500-c3fd-11e9-8d8f-5cea71f1ad8f.png">
<img width="934" alt="Capture5" src="https://user-images.githubusercontent.com/54170716/63414940-2962e500-c3fd-11e9-888d-bc303263612b.png">
<img width="609" alt="Capture6" src="https://user-images.githubusercontent.com/54170716/63414942-29fb7b80-c3fd-11e9-972e-ce74f0580827.png">

**Comment by yeb-skp** [comment]
After some investigations, it seems that it doesn't work because the package "later" is not installed. I have tried to install it from github but I can't.

**Comment by codebytere** [comment]
This does not seem to be an issue with Electron, rather an issue with `npm` and your local development setup. Should something change, please feel free to @ me in a follow-up comment.
