### ISSUE TITLE
DeadSimpleScreenSharing screen share is not working when initiated from Rocket.chat

### ISSUE THREAD

**Issue by ktnaane** [electron/electron-quick-start#311]
I have issues with screen sharing using deadsimplechreensharing integration.
The integration works fine, and creates a meeting. But when in a meeting, no one can see the shared screen, even if I share the screen, I don't become 'presenter', I remain a guest.
However, when the meeting is created from the WebBrowser extenstion(not via rocketchat), attendees can see the shared screen.

Rocket chat version 1.3.1. Running on a k8s cluster v1.14.0.

**Comment by codebytere** [comment]
This is not an issue with `electron-quick-start`, you should report it to rocket chat.
