### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by SqrtPapere** [electron/electron-quick-start#324]
Hi , 

I would like to obtain an exe from this boilerplate.

I am trying with this [guide](https://medium.com/how-to-electron/a-complete-guide-to-packaging-your-electron-app-1bdc717d739f), but I am getting the error:

```
C:\electron-quick-start>npm run dist

> electron-quick-start@1.0.0 dist C:\Users\frpegora\Desktop\electron_2\electron2\electron-quick-start
> build

'build' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 dist: `build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\frpegora\AppData\Roaming\npm-cache\_logs\2019-10-03T14_39_20_973Z-debug.log
```
What am I doing wrong?

**Comment by MRayermannMSFT** [comment]
Hey @SqrtPapere , I'd suggest using the README as a guide to using this repo. It includes up to date instructions on how to use/build/run it: https://github.com/electron/electron-quick-start/blob/master/README.md#to-use

**Comment by jaysongiroux** [comment]
hello, 
in order to build you will need a a package like this one: https://www.npmjs.com/package/electron-packager in order to build an exe.

**Comment by codebytere** [comment]
@SqrtPapere to run this repository locally, you should follow `To Use` as defined in our README: https://github.com/electron/electron-quick-start#to-use
