### ISSUE TITLE
electronv7.0.0 failed to install

### ISSUE THREAD

**Issue by luohao8023** [electron/electron-quick-start#328]
npm i
UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, lstat 'C:\Users\ADMINI~1\AppData\Local\Temp\electron-download-eMQeZQ\electron-v7.0.0-win32-x64.zip'

**Comment by xjtu-blacksmith** [comment]
I'm having the same problem ... I've tried on both my Windows system and Linux system, and I've got the same error.

**Comment by Xciyang** [comment]
I also got the same error.And I've tried switching mirrors.

**Comment by FoooooooF** [comment]
UnhandledPromiseRejectionWarning: RequestError: read ECONNRESET
    at ClientRequest.request.once.error (E:\webAssemble\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at ClientRequest.origin.emit.args (E:\webAssemble\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:6088) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6088) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN webAssemble@1.0.0 No description
npm WARN webAssemble@1.0.0 No repository field.

**Comment by mahonecode** [comment]
I'm having the same problem

**Comment by youlong723687543** [comment]
The same problem

**Comment by youlong723687543** [comment]
Looks like a system environment problem

**Comment by ZainChen** [comment]
The same problem

**Comment by jethromay** [comment]
Same issue for me.

**Comment by xjtu-blacksmith** [comment]
What a coincidence to face with such an error when using electron for the first time :sob:

**Comment by ZainChen** [comment]
6.0.0 version is normal

**Comment by yexiaodong** [comment]
Same issue for me.

**Comment by zhonggithub** [comment]
Same issue for me.  electron 6 is ok,  electron 7 error
in my mac book pro.  os is 10.15

**Comment by newwangzhicheng** [comment]
try `npm install electron-prebuilt -g `or `install electron-prebuilt --save-dev`,that's ok

**Comment by zeroyls** [comment]
Try:
1. npm_config_electron_mirror="https://npm.taobao.org/mirrors/electron/" npm_config_electron_custom_dir="7.0.0" npm install
2. npm start

**Comment by chengwengao** [comment]
> Try:
> 
> ```
> # 1. Install `cross-env`, used to set environment variables
> npm install -g cross-env
> # 2. Install dependencies, `npm_config_electron_custom_dir` needs equal to the version.
> cross-env npm_config_electron_mirror="https://npm.taobao.org/mirrors/electron/" npm_config_electron_custom_dir="7.0.0" npm install
> # 3. Run the app
> npm start
> ```
Solved my problem perfectly，thank you very much!

**Comment by heavenkiller2018** [comment]
thanks, i fixed it with the way finally!

**Comment by codebytere** [comment]
Closing as this is a mirroring problem that cannot unfortunately be fixed easily within the scope of quick-start.

**Comment by Dhailin** [comment]
You can use `cnpm install` instead of `npm install`  in China.
Fixed it.

**Comment by cnhuye** [comment]
> Try:
> 
> ```
> # 1. Install `cross-env`, used to set environment variables
> npm install -g cross-env
> # 2. Install dependencies, `npm_config_electron_custom_dir` needs equal to the version.
> cross-env npm_config_electron_mirror="https://npm.taobao.org/mirrors/electron/" npm_config_electron_custom_dir="7.0.0" npm install
> # 3. Run the app
> npm start
> ```

Thanks ！  I spend  hao ji tian on this problem。

**Comment by epsi95** [comment]
{
    "name": "name_of)your_app",
    "version": "1.0.0",
    "description": "",
    "main": "app.js",
    "scripts": {
        "start": "electron ."
    },
    "author": "your_name",
    "license": "ISC",
    **"devDependencies": {
        "electron": "^6.0.0"
    }**
}
