### ISSUE TITLE
Cannot read property 'whenReady' of undefined

### ISSUE THREAD

**Issue by Marcioshub** [electron/electron-quick-start#363]
after installing the modules and running npm start it gives me: TypeError: Cannot read property 'whenReady' of undefined

It seems that the tutorial doesn't work...

**Comment by codebytere** [comment]
@Marcioshub where are you seeing that? `whenReady` is not invoked in this repo.

**Comment by amanMahendroo** [comment]
Include require.js (using a CDN or any other method) and remove the 'content' attribute of the meta tag so your 'head' element now looks like this
`<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    
    <meta http-equiv="Content-Security-Policy" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>
  </head>
  `

**Comment by Tymski** [comment]
The error is on https://www.electronjs.org/docs/tutorial/first-app

**Comment by codebytere** [comment]
@Tymski what version of Electron are you using? I have no issues loading this into a [fiddle](https://github.com/electron/fiddle) and running it.

**Comment by malikasinger1** [comment]
@codebytere  it is in getting started program:
(I just started learning electron today and hello world program is not working, looking for help)

![image](https://user-images.githubusercontent.com/14273842/76709351-f75dfb00-671f-11ea-8277-1a03f32f5907.png)



full error message: 

```
admin@DESKTOP-6J3NI26 MINGW64 /c/_PROJECTS/_OPEN SOURCE/hello world Electron.js app
$ npm start

> hello-world-electron-js@1.0.0 start C:\_PROJECTS\_OPEN SOURCE\hello world Electron.js app
> node .

C:\_PROJECTS\_OPEN SOURCE\hello world Electron.js app\main.js:23
app.whenReady().then(createWindow)
    ^

TypeError: Cannot read property 'whenReady' of undefined
    at Object.<anonymous> (C:\_PROJECTS\_OPEN SOURCE\hello world Electron.js app\main.js:23:5)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-world-electron-js@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-world-electron-js@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-03-15T19_46_17_041Z-debug.log

admin@DESKTOP-6J3NI26 MINGW64 /c/_PROJECTS/_OPEN SOURCE/hello world Electron.js app
$
```



full main.js code: 
```
const { app, BrowserWindow } = require('electron')

function createWindow () {
  // Create the browser window.
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })

  // and load the index.html of the app.
  win.loadFile('index.html')

  // Open the DevTools.
  win.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', () => {
  // On macOS it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  // On macOS it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.

```


index.html:

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Hello World!</title>
    <!-- https://electronjs.org/docs/tutorial/security#csp-meta-tag -->
    <meta http-equiv="Content-Security-Policy" content="script-src 'self' 'unsafe-inline';" />
</head>

<body>
    <h1>Hello World!</h1>
    We are using node
    <script>document.write(process.versions.node)</script>,
    Chrome
    <script>document.write(process.versions.chrome)</script>,
    and Electron
    <script>document.write(process.versions.electron)</script>.
</body>

</html>
```

packege.json: 
```
{
  "name": "hello-world-electron-js",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "dependencies": {},
  "devDependencies": {
    "electron": "^8.1.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node ."
  },
  "keywords": [
    "electronjs",
    "nodejs"
  ],
  "author": "M.Inzamam Malik",
  "license": "MIT"
}

```

**Comment by malikasinger1** [comment]
# Solved
Problem Identified and fixed, hope they will accept my pull request,

the problem was ion packege.json, in start script it should be  `"start": "electron ."` instead of what it is

**Comment by ckerr** [comment]
> The error is on https://www.electronjs.org/docs/tutorial/first-app
> Note that this is only one of several issues with the tutorial on the website

@Tymski, please feel encouraged to file bug reports for the other issues. They can't be fixed if people don't know about them. Thanks!

**Comment by ijash** [comment]
why is this closed as the PR not yet merged?

**Comment by fregante** [comment]
This feels like an easy fix in Electron itself. If `.app` is being accessed while not inside `electron`,  throw a more informative message.

**Comment by brunoinds** [comment]
Another way to solve it is to check if you are running the command: `node .` instead of `npm start` 
I was working on another project with NodeJS and I confused the commands thinking `node .` was the command to start my electron app. Be sure you are typing `npm start`

**Comment by MxReaper** [comment]
I have this bug when using "start": "electron ."

**Comment by cherob** [comment]
I have this bug when using "start": "electron ." aswell...

**Comment by Sulavjung** [comment]
After executing command env, I find there is a environment variable ELECTRON_RUN_AS_NODE=1. (I have never set this variable...)

execute unset ELECTRON_RUN_AS_NODE in terminal, and confirm the variable does not exist anymore.

require('electron') can work now.

**Comment by capitanhazel** [comment]
I'm having this issue as of `electron ^33.0.2`

**Comment by Luther-Yang** [comment]
> 나는 지금 이 문제를 겪고 있어요`electron ^33.0.2`

file name chage 
eletron.js >>main.js

and package   "main": "main.js",
