### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by flik** [electron/electron-quick-start#375]
Here is detail:
` npm install
npm http GET https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/electron
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/xadmin/electron-quick-start
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/xadmin/electron-quick-start/npm-debug.log
npm ERR! not ok code 0
`

**Comment by codebytere** [comment]
This cannot be triaged. You have provided no code or reproducible information and the error:
> Error: CERT_UNTRUSTED

references codepaths not present in this repository. We can look to potentially triage this should more information come to light.
