### ISSUE TITLE
Can't start electron

### ISSUE THREAD

**Issue by LouiBelton** [electron/electron-quick-start#377]
Im running on windows 10 on a Dell Latitude E7470

I've just ran the forge boiler plate for electron
>npx create-electron-app crypto-app

But when i try to electron-forge start, it throws this error:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'start'
> 1 verbose cli ]
> 2 info using npm@6.14.4
> 3 info using node@v14.0.0
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle crypto-app@1.0.0~prestart: crypto-app@1.0.0
> 6 info lifecycle crypto-app@1.0.0~start: crypto-app@1.0.0
> 7 verbose lifecycle crypto-app@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle crypto-app@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\luibel59938\Documents\Electron\crypto-app\node_modules\.bin;C:\WINDOWS;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Shoreline Communications\ShoreWare Client\;C:\Program Files (x86)\Shoreline Communications\ShoreWare Client\win64;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\luibel59938\AppData\Local\Microsoft\WindowsApps;C:\Users\luibel59938\AppData\Local\atom\bin;C:\Users\luibel59938\AppData\Roaming\npm;C:\Users\luibel59938\AppData\Local\GitHubDesktop\bin;C:\Users\luibel59938\AppData\Local\Programs\Microsoft VS Code\bin
> 9 verbose lifecycle crypto-app@1.0.0~start: CWD: C:\Users\luibel59938\Documents\Electron\crypto-app
> 10 silly lifecycle crypto-app@1.0.0~start: Args: [ '/d /s /c', 'electron-forge start' ]
> 11 silly lifecycle crypto-app@1.0.0~start: Returned: code: 1  signal: null
> 12 info lifecycle crypto-app@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: crypto-app@1.0.0 start: `electron-forge start`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
> 14 verbose pkgid crypto-app@1.0.0
> 15 verbose cwd C:\Users\luibel59938\Documents\Electron\crypto-app
> 16 verbose Windows_NT 10.0.15063
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
> 18 verbose node v14.0.0
> 19 verbose npm  v6.14.4
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error crypto-app@1.0.0 start: `electron-forge start`
> 22 error Exit status 1
> 23 error Failed at the crypto-app@1.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by codebytere** [comment]
Please open this issue on `electron-forge.`
