### ISSUE TITLE
Electron Quick start App takes 2minute to load the url

### ISSUE THREAD

**Issue by malayaku** [electron/electron-quick-start#383]
url = 'http://webvizbench.com/Default.htm?skipdetect'
electron version = 6.1.9
chromium version = v76.0.3800.146
node = v12.4.0

**Do we have any known issue? How do we know, which one is the culprit here ?**
1. webpage 
2. electron app
3. chromium
4. node
5. environment (like CPU, RAM etc)

**Is there any tool, which can confirm the exact time consumed by above components?**

**Comment by codebytere** [comment]
Electron loads the URL as a function of your network - this is not an issue with Electron itself.
