### ISSUE TITLE
Cant start electropm

### ISSUE THREAD

**Issue by quantinfotech-fengzhichao** [electron/electron-quick-start#387]
![图片](https://user-images.githubusercontent.com/65530002/82418459-9a7c1980-9aaf-11ea-8026-24c63cea44ad.png)
my system environment is windows 10 and node version is v12.14.0, when i start electron then occur the proble in picture : Unable to  parse package.json.

**Comment by codebytere** [comment]
This is not enough information for us to proceed. How did you start electron? Did you follow the instructions provided?

**Comment by quantinfotech-fengzhichao** [comment]
![图片](https://user-images.githubusercontent.com/65530002/82518004-ed59dd80-9b50-11ea-806b-fa86f1a39507.png)
I fllowed the guide, clone the project, cpnm install and npm start, then I have trouble in start electron.I can't locate the problem, and there are no userful information in log. I guess it could be caused by environment  infact but I don't konw how to fix. my computer is HP laptop 14s.

**Comment by quantinfotech-fengzhichao** [comment]
this issue is caused by another encrypt software
