### ISSUE TITLE
with electron@9.0.0 the quick start does not open on windows 10

### ISSUE THREAD

**Issue by jonhallur** [electron/electron-quick-start#389]
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start

results in following error.

"C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" run start --scripts-prepend-node-path=auto

> electron-quick-start@1.0.0 start C:\Users\#######\code\electron\electron-quick-start
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 2147483651
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 2147483651
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\#######\AppData\Roaming\npm-cache\_logs\2020-05-28T21_36_24_692Z-debug.log

Process finished with exit code -2147483645

change electron version in package.json from "^9.0.0" to "^8.3.0" (like the previous version of the quickstart)
npm install again
now works fine and app opens.

this is windows 10, using the cmd terminal
node -v
v12.17.0

npm -v
6.14.5

**Comment by adsr303** [comment]
[Example log](https://github.com/electron/electron-quick-start/files/4702306/debug.log)

**Comment by csbarnes** [comment]
Got the similar error using Ubuntu shell and fixed it by running `npm i && npm start` in powershell instead. After it's working I was able to run it in Ubuntu.

**Comment by erickzhao** [comment]
I'm unable to repro on Windows 10 (Parallels) with Electron 9.0.0. Does an upgrade to Electron 10 help anyone?
