### ISSUE TITLE
npm run pack 无网络环境下失败

### ISSUE THREAD

**Issue by 524602075** [electron/electron-quick-start#400]
有网执行成功：
D:\dev\code\electron\electron-quick-start>npm run pack

> electron-quick-start@1.0.0 pack D:\dev\code\electron\electron-quick-start
> electron-builder --dir

  • electron-builder  version=22.7.0 os=10.0.18363
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@5.0.0 platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=9.1.0 appOutDir=dist\win-unpacked
  • default Electron icon is used  reason=application icon is not set

无网环境执行报错如下
D:\dev\code\electron\electron-quick-start>npm run pack

> electron-quick-start@1.0.0 pack D:\dev\code\electron\electron-quick-start
> electron-builder --dir

  • electron-builder  version=22.7.0 os=10.0.18363
  • writing effective config  file=dist\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@5.0.0 platform=win32 arch=x64
  ⨯ cannot execute  cause=exit status 1
                    out=
    > sqlite3@5.0.0 install D:\dev\code\electron\electron-quick-start\node_modules\sqlite3
    > node-pre-gyp install --fallback-to-build

    Failed to execute 'd:\Program Files\nodejs\node.exe C:\Users\52460\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\dev\code\electron\electron-quick-start\node_modules\sqlite3\lib\binding\napi-v3-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\dev\code\electron\electron-quick-start\node_modules\sqlite3\lib\binding\napi-v3-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=C:\Users\52460\.windows-build-tools\python27\python.exe' (1)

                    errorOut=node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp WARN Pre-built binaries not installable for sqlite3@5.0.0 and electron@9.1.0 (electron-v9.1 ABI, unknown) (falling back to source compile with node-gyp)
    node-pre-gyp WARN Hit error getaddrinfo ENOTFOUND mapbox-node-binary.s3.amazonaws.com
    gyp WARN install got an error, rolling back install
    gyp ERR! configure error
    gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
    gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
    gyp ERR! stack network settings.
    gyp ERR! stack     at Request.<anonymous> (C:\Users\52460\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\lib\install.js:170:21)
    gyp ERR! stack     at Request.emit (events.js:210:5)
    gyp ERR! stack     at Request.onRequestError (C:\Users\52460\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\request\request.js:881:8)
    gyp ERR! stack     at ClientRequest.emit (events.js:210:5)
    gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:406:9)
    gyp ERR! stack     at TLSSocket.emit (events.js:210:5)
    gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:92:8)
    gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
    gyp ERR! System Windows_NT 10.0.18363
    gyp ERR! command "d:\\Program Files\\nodejs\\node.exe" "C:\\Users\\52460\\AppData\\Roaming\\nvm\\v12.14.0\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=D:\\dev\\code\\electron\\electron-quick-start\\node_modules\\sqlite3\\lib\\binding\\napi-v3-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=D:\\dev\\code\\electron\\electron-quick-start\\node_modules\\sqlite3\\lib\\binding\\napi-v3-win32-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--python=C:\\Users\\52460\\.windows-build-tools\\python27\\python.exe"
    gyp ERR! cwd D:\dev\code\electron\electron-quick-start\node_modules\sqlite3
    gyp ERR! node -v v12.14.0
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'd:\Program Files\nodejs\node.exe C:\Users\52460\AppData\Roaming\nvm\v12.14.0\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=D:\dev\code\electron\electron-quick-start\node_modules\sqlite3\lib\binding\napi-v3-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=D:\dev\code\electron\electron-quick-start\node_modules\sqlite3\lib\binding\napi-v3-win32-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=C:\Users\52460\.windows-build-tools\python27\python.exe' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\dev\code\electron\electron-quick-start\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
    node-pre-gyp ERR! System Windows_NT 10.0.18363
    node-pre-gyp ERR! command "d:\\Program Files\\nodejs\\node.exe" "D:\\dev\\code\\electron\\electron-quick-start\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd D:\dev\code\electron\electron-quick-start\node_modules\sqlite3
    node-pre-gyp ERR! node -v v12.14.0
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! sqlite3@5.0.0 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sqlite3@5.0.0 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\52460\AppData\Roaming\npm-cache\_logs\2020-07-15T08_59_56_730Z-debug.log

                    command='d:\Program Files\nodejs\node.exe' 'C:\Users\52460\AppData\Roaming\nvm\v12.14.0\node_modules\npm\bin\npm-cli.js' rebuild sqlite3@5.0.0
                    workingDir=
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 pack: `electron-builder --dir`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 pack script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\52460\AppData\Roaming\npm-cache\_logs\2020-07-15T08_59_56_782Z-debug.log

工程package.json
{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "pack": "electron-builder --dir",
    "dist-win32": "electron-builder --win --ia32",
    "dist-win64": "electron-builder --win --x64",
    "dist-mac": "electron-builder --mac"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^9.1.0",
    "electron-builder": "^22.7.0"
  },
  "dependencies": {
    "sqlite3": "^5.0.0",
    "crypto-js": "^4.0.0",
    "node-xlsx": "^0.15.0"
  }
}

**Comment by codebytere** [comment]
Please open this issue on `electron-builder`. That repo is not maintained by the Electron team.
