### ISSUE TITLE
npm install electron error ?

### ISSUE THREAD

**Issue by haithamwaheed** [electron/electron-quick-start#406]
> core-js@3.6.5 postinstall /home/haitham/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> electron@9.1.2 postinstall /home/krypton/node_modules/electron
> node install.js

Downloading electron-v9.1.2-linux-x64.zip: [============] 100% ETA: 0.0 seconds 
Error: EACCES: permission denied, stat '/root/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv9.1.2SHASUMS256.txt/SHASUMS256.txt'
npm WARN enoent ENOENT: no such file or directory, open '/home/haitham/package.json'
npm WARN haitham No description
npm WARN haitham No repository field.
npm WARN haitham No README data
npm WARN haitham No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@9.1.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@9.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-01T14_44_48_845Z-debug.log

**Comment by oo6xoo** [comment]
I installed it with the help of this site 😁
https://circleci.com

**Comment by codebytere** [comment]
> '/root/.cache/electron/httpsgithub.comelectronelectronreleasesdownloadv9.1.2SHASUMS256.txt/SHASUMS256.txt'

@haithamwaheed this means you don't have write permissions configured properly on your machine and is not an issue with Electron.
