### ISSUE TITLE
Error: 140735290871808:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:532:

### ISSUE THREAD

**Issue by papakay** [electron/electron-quick-start#41]
Hi,

Please i've been trying to setup this quick start on my Mac but i kept on getting this error during npm install command.

I use mac osx 10.11.4

Please how can i resolve this issue?

**Comment by papakay** [comment]
Found the solution:

In El-capitan Openssl is not enabled by default except you add the information below to the environment variable.

export LDFLAGS="-L$/usr/local/opt/openssl/lib"
export CPPFLAGS="-I$/usr/local/opt/openssl/include"

Thanks.

**Comment by zeke** [comment]
Glad you got it worked out, @papakay. Thanks for updating the issue!
