### ISSUE TITLE
Not sure what to do

### ISSUE THREAD

**Issue by David263** [electron/electron-quick-start#412]
I forked this repo, which I think is the same as cloning it. But I can't figure out how to download or copy the main.js, index.html, and package.json files to my app directory so I can run the commands "npm install" and "npm start". The tutorials seem to assume one runs Linux, but I'm on Windows. Is there a Windows oriented tutuorial for node, npm, or Electron? Is there a specific online forum for Electron/Windows?

**Comment by codebytere** [comment]
@David263 forking and cloning are two [very different things](https://www.toolsqa.com/git/difference-between-git-clone-and-git-fork/#:~:text=When%20you%20fork%20a%20repository,with%20the%20help%20of%20Git.) :)

You should `cd` into the directory you wish to place this project in, and run:
```sh
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick start
$ npm install
$ npm start
```

**Comment by David263** [comment]
Follow-up: exactly what do "npm install" and "npm start" do? The documentation says that "npm install" installs the current repo. What does it mean to install a repo? Is the installation for the user or the computer (in Windows these are different)? Why can't the repo just be copied into the current directory and run there, like for documents and executable programs?

Is there a tutorial for beginning Windows users that explains all this? My basic motivation for asking is that npm seems to bring in gigabytes of files, even if I'm not using them. That's not nice. And if I allow it to install suggested additions for Electron (can't remember now what they are), that is 2 GB more. I don't mind 300 MB of support files, but gigabytes is wasting too much of my computer disk, space I need for editing large video files.
