### ISSUE TITLE
minimize and maximize does not work @ electron 10.1.0

### ISSUE THREAD

**Issue by IncinerateZ** [electron/electron-quick-start#417]
calling `remote.BrowserWindow.getFocusedWindow().minimize()` or `maximize()` on Windows 10 produces no results, logging `isMaximized()` or `isMinimized()` outputs false and logging the focused window outputs ... the focused window. Strangely enough only `close()` works.
isMaximizable, isMinimizable and resizable are all true.

**Comment by codebytere** [comment]
@IncinerateZ would you mind filling this out as an issue on `electron/electron` please?
