### ISSUE TITLE
Exit status 1 - on Raspberry Pi 2/ Pi3 with node 5.10/5.11 & npm 3.8.7

### ISSUE THREAD

**Issue by desq42** [electron/electron-quick-start#43]
Hi. 

`npm ERR! Linux 4.4.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! magicmirror@2.0.0 start:`electron js/electron.js`
npm ERR! Exit status 1
`
I tried several things. Reinstall of the Raspian. N
ew Node Version (6.0)

Has somebody an advice?

**Comment by desq42** [comment]
> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/electron-quick-start/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/pi/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron main.js' ]
12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-quick-start@1.0.0 start: `electron main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd /home/pi/electron-quick-start
17 error Linux 4.4.8-v7+
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.0.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error electron-quick-start@1.0.0 start: `electron main.js`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-quick-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-quick-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-quick-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jlord** [comment]
Hmm, I'm not really sure. I haven't tried this on a Raspberry Pi myself (though I hope to soon, just got a new one ✨ ) so I'm not sure if it has something to do with that or the new Node (or maybe not since you tried with others).

**Comment by RYG81** [comment]
I am having same issue on windows 10.
I have attached my log.

**Comment by RYG81** [comment]
Same issue here on windows 10.

**Comment by bk2dcradle** [comment]
As a temporary fix, revert back to a previous commit like so

```bash
git checkout HEAD~5  # Go back 5 commits

git checkout master     # Come back to master
```

**Comment by samradical** [comment]
I wasn't able to get it running on a RP3 either (node 6.2.0):
`npm ERR! Linux 4.1.18-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: electron main.js
npm ERR! Exit status 1`

Basically this issue: https://github.com/electron/electron/issues/4677, though there wasn't a conclusion really.
@jlord Please do and let us know the when you get up and running

**Comment by samelie** [comment]
Hi,
I build node from source which revealed this error Gtk...https://github.com/electron/electron/issues/2472
Turns out electron can only boot if its launched at startup. There is a mention of .config/autostart in the issue linked.
Making a new file in that directory with this worked!

[Desktop Entry]
Name=<some_name>
Exec=/usr/local/lib/node_modules/electron-prebuilt/dist/electron <path_to_app_directoy>
Type=application

**Comment by jlord** [comment]
@hamdipro opened a similar issue ☝️ which I'm cross referencing here. It looks like they are trying with a RP2 which is maybe `armv7l` and maybe should work? 😕 

Sadly, I still haven't booted mine up, but it's a 3 so I wouldn't be able to test for if it does work on 2 or not.

**Comment by hamdipro** [comment]
@jlord i got the same issue on RasperryPi3 
![screenshot from 2016-09-04 15-45-44](https://cloud.githubusercontent.com/assets/6583410/18231634/ad0b45be-72b6-11e6-9a09-cbb0ab68dc4f.png)
is there a solution ?

**Comment by jlord** [comment]
Hi, all 👋 

If you could, can you run `node -e 'console.log(process.arch, process.config.variables.arm_version)'` on your Pis and paste the output here? Thanks!

**Comment by jlord** [comment]
I set up my Raspberry Pi 3 and was able to successfully launch the quick start app.

I installed Node 4.5.0 via the [NodeSource distributions](https://github.com/nodesource/distributions) and when I run the command 👆 in the previous comment I get: `arm 7`.

I'm using Raspbian Jessie.

**Comment by manast** [comment]
```
root@DietPi:~# node -e 'console.log(process.arch, process.config.variables.arm_version)'
arm 6
```

**Comment by richardy706** [comment]
@jlord I just attempted to launch the quick-start app.  It failed with a very similar stack trace as @manast.  I am using a Pi3 running Raspbian Jessie and the above command returns arm7.   Any help is appreciated.

````
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/share/electron-quick-start/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/pi/share/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd /home/pi/share/electron-quick-start
17 error Linux 4.4.13-v7+
````

**Comment by manast** [comment]
@richardy706 I managed to get it working using resin.io. It should be possible to replicate resin.io environment if you do not want to use their service: https://github.com/resin-io/resin-electronjs

**Comment by Haacked** [comment]
@richardy706 did @manast's advice help? @desq42 are you still unable to get this working?

**Comment by richardy706** [comment]
Resin.io is not an option for me; so, no the advice did not help me.   I have not looked at this issue since my post.

**Comment by polyamide** [comment]
don't forget to specify the display, if you run electron over SSH.

```
pi@pi-1:~/projects/electron-quick-start $ export DISPLAY=:0
pi@pi-1:~/projects/electron-quick-start $ npm run start
```

**Comment by jacobgus** [comment]
Im assuming there has not been a fix for this issue? Im having the same issues as the first guy with a RPi3 working on the MagicMirror. Ive tried a crap load of fixes including everything in this thread with the exception of running on bootup. Can anyone testify if that worked or not?

**Comment by robozera** [comment]
hey guys... it's 2017... I'm using the new version and still getting the same error.

magicmirror@2.1.0 start: 'electron js/electron.js'
Exit status 1

**Comment by chrbongardt** [comment]
Hi, I'm also getting same error. Using RPI 3 on Jessie and latest stable node 7.x. Any fix for this?

**Comment by samradical** [comment]
Electron could need to boot with the OS . Check for autorun

**Comment by darkcloud784** [comment]
I can also confirm the same error on my pi 3b.

**Comment by codebytere** [comment]
Closing due to staleness, happy to re-open should more information come to light!
