### ISSUE TITLE
argument containing ':' can not be followed with another argument

### ISSUE THREAD

**Issue by Pisamad** [electron/electron-quick-start#432]
After installing electron-quick-start, I tested the cli argument:
It works:
`.\node_modules\.bin\electron.cmd .`
`.\node_modules\.bin\electron.cmd . foo`
`.\node_modules\.bin\electron.cmd . foo bar`
`.\node_modules\.bin\electron.cmd . foo:bar`

But this, no (no browser launched):
`.\node_modules\.bin\electron.cmd . foo:bar bar`

In other words, as soon as an argument contains ':', it cannot be followed by another argument.

Why ?

**Comment by erickzhao** [comment]
Hey @Pisamad! Thanks for the report. This seems to be related to electron/electron#16889 and unrelated to the contents of this repo.

There's a workaround available in the original issue where you can do the following to run your app properly with that exact set of args:

```
.\node_modules\.bin\electron.cmd . -- foo:bar bar
```
