### ISSUE TITLE
Electron 12.0.0 'Require' is not defined

### ISSUE THREAD

**Issue by mihir-chauhan** [electron/electron-quick-start#463]
Hey!

I am running into a problem using this quick start. Before I package the app, everything works fine and the node 'require' works fine without errors. However, when I use `electron-packager` and try out the `.exe`, it gives an error ar line 1 that 'require' is not defined:

```
const { app, BrowserWindow } = require('electron')
```

I have tried with and without `nodeIntegration` but it doesn't seem to change the error. Here is my `createWindow()` function:

```
mainWindow = new BrowserWindow({
    width: 500,
    height: 600,
    webPreferences: {
      nodeIntegration: true,
      // preload: path.join(__dirname, 'preload.js'),
    },
    resizable: false,
    icon: 'logo.png',
    frame: false
  })

  mainWindow.setMenuBarVisibility(false)

  // and load the index.html of the app.
  mainWindow.loadFile('index.html')

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()
```

Thank you!

**Comment by gaolingxiao** [comment]
Same problem here.

**Comment by gaolingxiao** [comment]
My case says require is not defined in renderer.js

This is my renderer.js
`const { ipcRenderer } = require('electron')`

**Comment by codebytere** [comment]
This is [expected](https://github.com/electron/electron/blob/master/docs/tutorial/context-isolation.md) with the `contextIsolation` default change.

**Comment by ifcquery** [comment]
Hi,

after recent changes in electron, 99% of the examples with native modules out there don't work any more.
Is there any working example that compiles and runs with the current node and electron?

**Comment by updatesvc** [comment]
> Hi,
> 
> after recent changes in electron, 99% of the examples with native modules out there don't work any more.
> Is there any working example that compiles and runs with the current node and electron?
@ifcquery 
```Javascript
const win = new BrowserWindow({      
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false
        }
    })
```

However, I do not know the exact implications of [**contextIsolation**](https://github.com/electron/electron/blob/master/docs/tutorial/context-isolation.md)

**Comment by SmolinPavel** [comment]
@updatesvc thanks, this has helped to solve the issue. I'm also worried if setting `contextIsolation` is a good idea, but at least it fixes the `require` issue.

**Comment by artium-ryanh** [comment]
@codebytere If this issue is expected, how do we import a renderer script into our index.html file without turning on Node integration and turning off context isolation? As far as I understand their defaults are meant to protect the user from malicious code.

**Comment by Quang-deeptry** [comment]
> Hey!
> 
> I am running into a problem using this quick start. Before I package the app, everything works fine and the node 'require' works fine without errors. However, when I use `electron-packager` and try out the `.exe`, it gives an error ar line 1 that 'require' is not defined:
> 
> ```
> const { app, BrowserWindow } = require('electron')
> ```
> 
> I have tried with and without `nodeIntegration` but it doesn't seem to change the error. Here is my `createWindow()` function:
> 
> ```
> mainWindow = new BrowserWindow({
>     width: 500,
>     height: 600,
>     webPreferences: {
>       nodeIntegration: true,
>       // preload: path.join(__dirname, 'preload.js'),
>     },
>     resizable: false,
>     icon: 'logo.png',
>     frame: false
>   })
> 
>   mainWindow.setMenuBarVisibility(false)
> 
>   // and load the index.html of the app.
>   mainWindow.loadFile('index.html')
> 
>   // Open the DevTools.
>   // mainWindow.webContents.openDevTools()
> ```
> 
> Thank you!

### I added these to BrowserWindow and it works fine

**nodeIntegration: true,
contextIsolation: false,
enableRemoteModule: true,**

**Comment by BrendonChirume** [comment]
> @codebytere If this issue is expected, how do we import a renderer script into our index.html file without turning on Node integration and turning off context isolation? As far as I understand their defaults are meant to protect the user from malicious code.

@codebytere  you raised a very important solution I think. I'm trying to use preload.js and react so contextIsolation has to be true for me to be able to use it but then it starts to give the same error

**Comment by artium-ryanh** [comment]
For anyone wondering how to avoid turning on Node Integration or turning off Context Isolation: My team used [this template project](https://github.com/diego3g/electron-typescript-react) to get started. It is a Typescript React app that does not use `create-react-app`, so it may not be exactly what you're looking for. However, it is small and easy to understand, it's possible you could adapt some other framework to use the same principles.

**Comment by hwoodall30** [comment]
@artium-ryanh  Any chance you could help get this going with a Next.js-Electron Application?

**Comment by artium-ryanh** [comment]
No, I'm sorry. I'm far from an expert on this issue. I just started from the template project that I linked to and played with it until it met my needs. I couldn't set up another React/Electron app with different tooling.

**Comment by hwoodall30** [comment]
Could you explain where the MAIN_WINDOWS_WEBPACK_ENTRY and MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY are coming from?

**Comment by Manndung75** [comment]
A

**Comment by mlumoura** [comment]
Boa noite. No meu código, uso const {remote} = require('electron'); em um aquivo. Uso o require(électron´) mas o erro que o console acusa é somente nesta chamada.  webPreferences: {
      nodeIntegration: true,
      contextIsolation: true
    }
Já alterei esses parêmtros e nada adiantou.

**Comment by erickzhao** [comment]
@mlumoura The `remote` module was removed in Electron 14. If you _really_ need to migrate an older project to newer versions of Electron, see: https://github.com/electron/remote

Otherwise, please use the IPC modules directly: https://www.electronjs.org/docs/latest/tutorial/ipc

**Comment by deniafe** [comment]
For everyone still looking for a solution, this should work. I am using ipcRenderer as an example, but it should work for any node module that you need to require.

In your browser window, set nodeIntegration and contextIsolation to true. Also add a preload option.

 It should look like this 
    
    ` mainWindow = new BrowserWindow({
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.js'),
    }
  });`
  
  In preload.js, add this

`const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ipcRenderer', {
  send: (channel, data) => ipcRenderer.send(channel, data),
  on: (channel, func) =>
    ipcRenderer.on(channel, (event, ...args) => func(...args)),
});`

What the proload.js script does is it has exposed the module needed to the renderer.

So, in your renderer js file, do not require ipcRenderer (or any other node module). Just use it directly and it should work
