### ISSUE TITLE
button issues

### ISSUE THREAD

**Issue by hohuy852** [electron/electron-quick-start#477]
Uncaught TypeError: window.minimizeWindow is not a function
Uncaught TypeError: window.openMenu is not a function
Uncaught TypeError: window.maxUnmaxWindow is not a function
Uncaught TypeError: window.closeWindow  is not a function
![image](https://user-images.githubusercontent.com/57467992/115186525-180b3800-a10c-11eb-9032-4ac0817fd3b7.png)

**Comment by gabery** [comment]
[_**@![image](https://user-images.githubusercontent.com/75150129/118100293-f6396400-b3de-11eb-9b0e-26c6ec66aed9.gif)**_]()

**Comment by malept** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports specifically relating to the code in quick start (and not any new code you add for your project), so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

I hope this helps!
