### ISSUE TITLE
Error trying electron-quick-start on RPI2

### ISSUE THREAD

**Issue by benjeefox** [electron/electron-quick-start#48]
Hi,
Tried to Install electron-quick-start on a Raspberry pi 2, Raspbian 
Distributor ID: Raspbian
 Description: Raspbian GNU/Linux 8.0 (jessie)
 Release: 8.0
 Codename: jessie

results is:

electron-quick-start@1.0.0 start /home/pi/MagicMirror/electron-quick-start
 electron main.js

npm ERR! Linux 4.1.19-v7+
 npm ERR! argv “/usr/local/bin/node” “/usr/local/bin/npm” "start"
 npm ERR! node v6.1.0
 npm ERR! npm v3.8.6
 npm ERR! code ELIFECYCLE
 npm ERR! electron-quick-start@1.0.0 start: electron main.js
 npm ERR! Exit status 1
 npm ERR!
 npm ERR! Failed at the electron-quick-start@1.0.0 start script ‘electron main.js’.
 npm ERR! Make sure you have the latest version of node.js and npm installed.
 npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
 npm ERR! not with npm itself.
 npm ERR! Tell the author that this fails on your system:
 npm ERR! electron main.js
 npm ERR! You can get information on how to open an issue for this project with:
 npm ERR! npm bugs electron-quick-start
 npm ERR! Or if that isn’t available, you can get their info via:
 npm ERR! npm owner ls electron-quick-start
 npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
 npm ERR! /home/pi/MagicMirror/electron-quick-start/npm-debug.log

pi@mirror2:~/MagicMirror/electron-quick-start $ cat /home/pi/MagicMirror/electron-quick-start/npm-debug.log
 0 info it worked if it ends with ok
 1 verbose cli [ ‘/usr/local/bin/node’, ‘/usr/local/bin/npm’, ‘start’ ]
 2 info using npm@3.8.6
 3 info using node@v6.1.0
 4 verbose run-script [ ‘prestart’, ‘start’, ‘poststart’ ]
 5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
 6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
 7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
 8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
 9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/pi/MagicMirror/electron-quick-start/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
 10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/pi/MagicMirror/electron-quick-start
 11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ ‘-c’, ‘electron main.js’ ]
 12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1 signal: null
 13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
 14 verbose stack Error: electron-quick-start@1.0.0 start: electron main.js
 14 verbose stack Exit status 1
 14 verbose stack at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
 14 verbose stack at emitTwo (events.js:106:13)
 14 verbose stack at EventEmitter.emit (events.js:191:7)
 14 verbose stack at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
 14 verbose stack at emitTwo (events.js:106:13)
 14 verbose stack at ChildProcess.emit (events.js:191:7)
 14 verbose stack at maybeClose (internal/child_process.js:850:16)
 14 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 15 verbose pkgid electron-quick-start@1.0.0
 16 verbose cwd /home/pi/MagicMirror/electron-quick-start
 17 error Linux 4.1.19-v7+
 18 error argv “/usr/local/bin/node” “/usr/local/bin/npm” "start"
 19 error node v6.1.0
 20 error npm v3.8.6
 21 error code ELIFECYCLE
 22 error electron-quick-start@1.0.0 start: electron main.js
 22 error Exit status 1
 23 error Failed at the electron-quick-start@1.0.0 start script ‘electron main.js’.
 23 error Make sure you have the latest version of node.js and npm installed.
 23 error If you do, this is most likely a problem with the electron-quick-start package,
 23 error not with npm itself.
 23 error Tell the author that this fails on your system:
 23 error electron main.js
 23 error You can get information on how to open an issue for this project with:
 23 error npm bugs electron-quick-start
 23 error Or if that isn’t available, you can get their info via:
 23 error npm owner ls electron-quick-start
 23 error There is likely additional logging output above.
 24 verbose exit [ 1, true ]
 

Any idea ?

thank you....

**Comment by jlord** [comment]
Closing here to track as a dupe in #43
