### ISSUE TITLE
@types/node@https://registry.npm.taobao.org/@types/node/-/node-14.17.0.tgz' is not in the npm registry

### ISSUE THREAD

**Issue by yuwangjuan** [electron/electron-quick-start#487]
when i use npm install ,the erroris below:'@types/node@https://registry.npm.taobao.org/@types/node/-/node-14.17.0.tgz' is not in the npm registry.      
npm ERR! 404 You should bug the author to publish it

**Comment by yuesong-feng** [comment]
I met this problem too.

**Comment by yuesong-feng** [comment]
After I change the npm registry to default, it worked. 
`npm config set registry https://registry.npmjs.org/`
But the download process is so slow and even failed. 
It's probably a problem with tabao registry.
