### ISSUE TITLE
Start error on windows 10

### ISSUE THREAD

**Issue by OmarAttrash** [electron/electron-quick-start#54]
`Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 3221225781
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

I have tried ever thing that I cloud think of: installing electron-prebuilt locally/globally updating Nodejs, and it doesn't seems to work.

**Comment by OmarAttrash** [comment]
Solved it! 
vcruntime140.dll and msvcp140.dll were missing for windows you can download them from here 
https://www.microsoft.com/en-us/download/details.aspx?id=48145 that should solve the problem.

**Comment by TriMoon** [comment]
#55

**Comment by jlord** [comment]
This should be fixed in Electron v1.1.1 which we've just updated this repo to use 👍
