### ISSUE TITLE
npm start failed on Windows 10

### ISSUE THREAD

**Issue by WernerBuchert** [electron/electron-quick-start#56]
npm start fails with this log-file (BTW, I habe installed Visual C++ Redistributable for Visual Studio 2015).

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Programme\\nodejs\\node.exe',
1 verbose cli   'C:\\Programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart electron-quick-start@1.0.0
6 info start electron-quick-start@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info electron-quick-start@1.0.0 Failed to exec start script
9 verbose stack Error: electron-quick-start@1.0.0 start: `electron main.js`
9 verbose stack Exit status 3221225595
9 verbose stack     at EventEmitter.<anonymous> (C:\Programme\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Programme\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electron-quick-start@1.0.0
11 verbose cwd C:\Users\Werner\electron-quick-start
12 error Windows_NT 10.0.10586
13 error argv "C:\\Programme\\nodejs\\node.exe" "C:\\Programme\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error node v4.2.4
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error electron-quick-start@1.0.0 start: `electron main.js`
17 error Exit status 3221225595
18 error Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
18 error This is most likely a problem with the electron-quick-start package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron main.js
18 error You can get their info via:
18 error     npm owner ls electron-quick-start
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by WernerBuchert** [comment]
Sorry for my poor English or English with German: 
I've installed Visual C++ Redistributable for Visual Studio 2015

**Comment by jlord** [comment]
I believe this has been fixed in the latest version of Electron which we're about to add to the quick start. Please reopen if you try the new version and the problem persists.
