### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by smallfish01** [electron/electron-quick-start#565]
I install electron as the below steps:
# git clone https://github.com/electron/electron-quick-start
# cd electron-quick-start
# npm install 
# npm start
When I running "npm start" and got the error:
> electron-quick-start@1.0.0 start /opt/electron-quick-start
> electron .

[1220/053909.117691:FATAL:electron_main_delegate.cc(290)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/opt/electron-quick-start/node_modules/electron/dist/electron exited with signal SIGTRAP
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-20T05_39_09_322Z-debug.log

Also when I running "npm start --no-sandbox" also got the same error.

Please advise.

Thank you very much.

**Comment by erickzhao** [comment]
When running an NPM script, you need to add `--` to pass arguments to the Electron binary rather than to `npm` itself.

```
npm start -- --no-sandbox
```

See https://stackoverflow.com/questions/43046885/what-does-do-when-running-an-npm-command
