### ISSUE TITLE
Electron ..Not able to package for a windows from a Mac?

### ISSUE THREAD

**Issue by zacharydavidwhyteweatherall** [electron/electron-quick-start#57]
Trying to package a windows version from a mac . Have easily packaged for darwin (mac) works perfectly but when trying to package --platform=all --arch=all doesn't work and ill attach a screen shot of what it comes up when trying to package for Windows.

![screen shot 2016-05-23 at 12 09 40 pm](https://cloud.githubusercontent.com/assets/17302253/15457526/400aefec-20df-11e6-9e7e-87af42fcdf07.png)
![screen shot 2016-05-23 at 12 09 14 pm](https://cloud.githubusercontent.com/assets/17302253/15457527/400bb8e6-20df-11e6-8834-c1b6a7ed3bd7.png)

**Comment by zacharydavidwhyteweatherall** [comment]
{
  "name": "engagingContracts",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-packager ./ --platform=win32 --arch=all"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/electron/electron-quick-start.git"
  },
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "build"

  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "bugs": {
    "url": "https://github.com/electron/electron-quick-start/issues"
  },
  "homepage": "https://github.com/electron/electron-quick-start#readme",
  "devDependencies": {
    "electron-packager": "^7.0.2",
    "electron-prebuilt": "^0.37.0"
  }
}

**Comment by jlord** [comment]
You are able to package an Electron app for Windows from a Mac but you need to have a few dependencies on your computer first to do so. 

Here is the section on [those dependencies](https://github.com/electron-userland/electron-packager#building-windows-apps-from-non-windows-platforms) from the `electron-packager` readme. 

Hopefully that helps! I'm closing out here as this isn't an Electron Quick Start issue.
