### ISSUE TITLE
Incorrect Discord invite link in the Menu

### ISSUE THREAD

**Issue by alabhyajindal** [electron/electron-quick-start#589]
The Discord invite link under Help -> Community Discussions leads to https://discord.com/invite/electron which is incorrect. 
The correct invite link should be: https://discord.com/invite/APGC3k5yaH

<img width="591" alt="image" src="https://user-images.githubusercontent.com/52493077/159407605-990bca38-c33e-4a72-ad82-f7eeb90bfaf9.png">

**Comment by wigzen** [comment]
This issue has been resolved
