### ISSUE TITLE
npm install && npm start error

### ISSUE THREAD

**Issue by paulkramme** [electron/electron-quick-start#59]
When i type `npm install && npm start` this comes as output
```
sh: 1: node: not found
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.2.1 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.2.1 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/paul/github/electron-quick-start/npm-debug.log
```

[npm-debug_log.txt](https://github.com/electron/electron-quick-start/files/294093/npm-debug_log.txt)

**Comment by jlord** [comment]
> `sh: 1: node: not found`

Hmm. Do you have node on your path? When you type `node` into your terminal do you get the node repl? 

```bash
$ node
# > 
```

**Comment by paulkramme** [comment]
Damned. `sudo apt-get install nodejs-legacy` fixed my problem. I thought it would be included. Thanks for your advice.

**Comment by sayantanHack** [comment]
same issue happening in windows.This is showing bellow
error code ELIFECYCLE
 error errno 1
 error electron-quick-start@1.0.0 start: `electron .`
 error Exit status 1
 error Failed at the electron-quick-start@1.0.0 start script.
 error This is probably not a problem with npm. There is likely additional logging output above.
 verbose exit [ 1, true ]
