### ISSUE TITLE
Rshiny App blank screen after build

### ISSUE THREAD

**Issue by leehweeling** [electron/electron-quick-start#627]
Hi,

I was using the default R script in the folder to test if it works. I've also installed all the R packages that are required ("shiny", "tidyverse", "plotly", "DT", "lubridate", "reshape2" as examples). However, after running "npm run package-win", and I opened electron-quick-start in ElectronShinyAppWindows folder, I only get a blank screen. I tried to force reload, but only the blank screen remained. I've searched everywhere for a possible solution, but could not find any. Could someone please help?

Thanks.

Best regards,
Hweeling

**Comment by PetrStanik** [comment]
https://github.com/electron/electron-quick-start/issues/627#issue-1328322816
