### ISSUE TITLE
can not run quick start app

### ISSUE THREAD

**Issue by smallg** [electron/electron-quick-start#64]
`npm install` command run success, but run `npm start` throw some issue:
![image](https://cloud.githubusercontent.com/assets/225962/16221150/c8ab44a0-37c3-11e6-94c0-15991955b1b8.png)

**Comment by smallg** [comment]
it's my fault, `npm install` can not install successfully.

**Comment by zeke** [comment]
Thanks for following up, @smallg. Happy hacking!
