### ISSUE TITLE
Tutorial link provided in README is dead

### ISSUE THREAD

**Issue by XRFXLP** [electron/electron-quick-start#650]
In [this](https://www.electronjs.org/docs/latest/tutorial/tutorial-1-prerequisites) the hyperlink of Tutorial is [dead](https://www.electronjs.org/docs/latest/tutorial/tutorial-1-prerequisites)

![image](https://user-images.githubusercontent.com/23459568/192588107-c99d843a-dfd0-4c3c-9f4b-212685068495.png)

**Comment by DemonicArthas** [comment]
I believe [this](https://www.electronjs.org/docs/latest/tutorial/tutorial-prerequisites) is the new link that should be in the README

**Comment by erickzhao** [comment]
sorry about that [e86dffc](https://github.com/electron/electron-quick-start/commit/e86dffc6b1fbc96a9d485501ffdb3ae5b1c1ca84)
