### ISSUE TITLE
very simple questions, Please help!

### ISSUE THREAD

**Issue by szjfhb** [electron/electron-quick-start#66]
I have a very simple page just embed a simplepage in webview.
and my object is to print to PDF for the webview, and try to print all of it, not only the 1 page of it.
Now I want access the webview in mainthread, but blocked..

webview seems only can access in render process, but print must send to main process =,=
I don't how to handle it now.

Any suggestion?

some code related:
```html
//index.html
  <body>
    <h1>Hello World!</h1>
    <!-- All of the Node.js APIs are available in this renderer process. -->
    We are using node <script>document.write(process.versions.node)</script>,
    Chromium <script>document.write(process.versions.chrome)</script>,
    and Electron <script>document.write(process.versions.electron)</script>.
    <button class="demo-button" id="print-pdf">Print PDF</button>
    <webview id="allPage" src="SimplePage.htm" ></webview>
  </body>
```
```javascript
//render process
const ipcR = require('electron').ipcRenderer

const printPDFBtn = document.getElementById('print-pdf')

printPDFBtn.addEventListener('click', function (event) {
  ipcR.send('print-to-pdf')
})
```
```javascript
//main process
ipc.on('print-to-pdf', function (event) {
  const pdfPath = path.join(os.tmpdir(), 'print.pdf')
  const win = BrowserWindow.fromWebContents(event.sender)
  //use someway to get the webview....
 var webview = getwebview()...//not ready here.  
webview .printToPDF({}, function (error, data) {
    if (error) throw error
    fs.writeFile(pdfPath, data, function (error) {
      if (error) {
        throw error
      }
      shell.openExternal('file://' + pdfPath)
      //event.sender.send('wrote-pdf', pdfPath)
    })
  })
})
```
Thanks.

**Comment by szjfhb** [comment]
=.= maybe i should try directly printtopdf on render process?

**Comment by zeke** [comment]
Hey @szjfhb, check out https://github.com/electron/electron-api-demos -- it includes a printing demo! 📜

**Comment by szjfhb** [comment]
@zeke hi, thanks Zeke.
I have just finished it.  
I want to obey the demo to print PDF on main thread, but can't find a way to access the webview in main thread.
Now i directly access the webview and print it on render thread. it works.

Any comment on this? @zeke 

Thanks.
