### ISSUE TITLE
Help! what happen??

### ISSUE THREAD

**Issue by longboy** [electron/electron-quick-start#68]
![11111](https://cloud.githubusercontent.com/assets/6941888/16706792/3b399798-45ec-11e6-9fec-19a4c001d2e5.png)

**Comment by MarshallOfSound** [comment]
Looks like you are having network issues, possibly on a dodgy network or behind a firewall/proxy

**Comment by zeke** [comment]
> `ECONNRESET` (Connection reset by peer): A connection was forcibly closed by a peer. This normally results from a loss of the connection on the remote socket due to a timeout or reboot. 

Like @MarshallOfSound said, probably just a network blip.
