### ISSUE TITLE
Problems to run 'npm start'

### ISSUE THREAD

**Issue by Wernthaler** [electron/electron-quick-start#69]
I have some trouble to run 'npm start' after cloning and installing the 'electron-quick-start' project from Github.
I use a fresh Fedora Workstation Installation (fc24.x86_64) virtualized on VMware.

Please see the attached screen dump.

![electron-quick-start-failure](https://cloud.githubusercontent.com/assets/20271294/16707475/4c6ca414-45cf-11e6-9bca-dc77a3f8aa33.png)

I can't locate the missing lib file 'libXss.so.1'. Please help.

Thanks for your support.

**Comment by MarshallOfSound** [comment]
An initial search reveals that `libXss.so` is provided on fedora by `libXScrnSaver`

You should try `yum install libXScrnSaver`

**Comment by Wernthaler** [comment]
@MarshallOfSound : Thanks, your helped me to solve my problem! :+1: 

But can you tell me, why 'electron-quick-start' needs a lib from libXScrnSaver package?

**Comment by MarshallOfSound** [comment]
@Wernthaler I have no idea, but it would be Chromium that requires it not electron exactly.
