### ISSUE TITLE
The app automatically shows the Chrome Inspect tools right after start up...

### ISSUE THREAD

**Issue by junerockwell** [electron/electron-quick-start#76]
I followed the instructions. And once the app started, the Chrome Dev tools just show up after a second. Is there a way to turn this off for production?

![screen shot 2016-08-19 at 2 52 20 pm](https://cloud.githubusercontent.com/assets/5051574/17825274/2c0a6b1c-661c-11e6-91a6-9fa2f6d81f7d.png)

**- Running on MacOSX El Capital 10.11.6**
**- Node v0.12.7**
**- npm 2.11.3**
**- Chrome Version 52.0.2743.116 (64-bit)** As of now, it is up to date.

**Comment by zeke** [comment]
To turn it off, just remove or comment out this line in `main.js`:

```js
mainWindow.webContents.openDevTools()
```

That's it!

**Comment by jlord** [comment]
These lines specifically: https://github.com/electron/electron-quick-start/blob/master/main.js#L18-L19
