### ISSUE TITLE
failed with electrin node install.js script: Error: read ECONNRESET

### ISSUE THREAD

**Issue by jns4u** [electron/electron-quick-start#77]
I am trying to install electron -quick-start on linux 32 bit system but getting following error.

> electron@1.3.3 postinstall /home/chanakya/Desktop/Projects/Imran/Node-UI/Other/electron-quick-start-master/node_modules/electron
> node install.js

Downloading electron-v1.3.3-linux-ia32.zip
Error: read ECONNRESET
/home/chanakya/Desktop/Projects/Imran/Node-UI/Other/electron-quick-start-master/node_modules/electron/install.js:22
  throw err
        ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
npm ERR! Linux 4.0.0-kali1-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "electron" "--save-dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! electron@1.3.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.3.3 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

**Comment by MarshallOfSound** [comment]
This appears to be a one off network issue.  Are you behind a proxy / firewall?

It will probably work if you delete your node_modules folder and try again

**Comment by jns4u** [comment]
no firewalls at all, but i find it seems to be network issue, although i manage to install this by configuring network properties.

Thanks for reply.
