### ISSUE TITLE
Using sqlite3, it appears that the sqlite3 module is not found after compilation.

### ISSUE THREAD

**Issue by yang19841021** [electron/electron-quick-start#779]
![image](https://github.com/electron/electron-quick-start/assets/29669946/867981ca-6544-4f98-bb5b-9e02ab4c6161)

Using sqlite3, it appears that the sqlite3 module is not found after compilation.
Execute the compiled command

electron-packager . app --win --out presenterTool --arch=x64 --electron-version 24.3.0 --overwrite --ignore=node_modules

**Comment by codebytere** [comment]
Electron packager is not maintained by the Electron team. Additionally, sqlite3 is not found in this repository.
