### ISSUE TITLE
# Go into the repository

### ISSUE THREAD

**Issue by Gutodotado24** [electron/electron-quick-start#784]
app.getLocale() // 'de'
app.getSystemLocale() // 'fi-FI'
app.getPreferredSystemLanguages() // ['fr-CA', 'en-US', 'zh-Hans-CN', 'fi', 'es-419']

**Comment by codebytere** [comment]
This issue does not identify a bug or issue with https://github.com/electron/electron-quick-start - with what's given we can't move forward or triage this. If you are experiencing a bug, you are welcome to follow up with more information and we could re-consider or re-invesigate.
