### ISSUE TITLE
Typescript version ?

### ISSUE THREAD

**Issue by mmc41** [electron/electron-quick-start#80]
Would be nice with a typescript 2.0 version of the quick start (and typings for the electron project if they are not already there in the npms).

**Comment by jlord** [comment]
I've applied a help wanted label here, if someone wanted to fork this and create a typescript version that would be nice ✨

**Comment by zeke** [comment]
Here's @Haringat's TypeScripty branch: https://github.com/Haringat/electron-quick-start/tree/typescript
