### ISSUE TITLE
Permission Issue for electron execution

### ISSUE THREAD

**Issue by jns4u** [electron/electron-quick-start#81]
My entire project is setup on linux distro. Previously it was working fine. Recently i moved entire file structure to disk mounted with widows file system now i am accessing project from there into linux. But after installing dependencies and running command $npm start into project root folder i am getting 
Permission denied issue. below mentioned is the error details.

> electron-quick-start@1.0.0 start /media/chanakya/B4CCD876CCD83478/Backup/KaliLinux/Projects/Imran/Node-UI/MobiMe_extremely_small
> electron .

sh: 1: electron: Permission denied

npm ERR! Linux 4.0.0-kali1-686-pae
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! This is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
 
I appreciate any help in this regards.

**Comment by MarshallOfSound** [comment]
This doesn't seem like an `electron-quick-start` issue.

I would recommend reinstalling your `node_modules` directory completely.  Sometimes when copying `node_modules` from OS to OS the executable permissions get very confused.

If deleting and reinstalling the `node_modules` directory doesn't help, you can raise this as an issue over at [`electron-prebuilt`](https://github.com/electron-userland/electron-prebuilt)
