### ISSUE TITLE
ubuntu 'npm start' fail

### ISSUE THREAD

**Issue by homerzhou** [electron/electron-quick-start#83]
npm install is ok, and npm start is fail,   'npm-debug.log' is follow:

```bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 silly lifecycle electron-quick-start@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
8 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/root/electron/electron-quick-start/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /root/electron/electron-quick-start
11 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
14 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack       at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack       at emitTwo (events.js:87:13)
14 verbose stack       at EventEmitter.emit (events.js:172:7)
14 verbose stack       at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack       at emitTwo (events.js:87:13)
14 verbose stack       at ChildProcess.emit (events.js:172:7)
14 verbose stack       at maybeClose (internal/child_process.js:821:16)
14 verbose stack       at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid electron-quick-start@1.0.0
16 verbose cwd /root/electron/electron-quick-start
17 error Linux 3.13.0-43-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron-quick-start package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron-quick-start
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron-quick-start
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by duwke** [comment]
same issue.  Ubuntu 16.04
I tried changing over to the nodesource 4.5 nodejs.  Same issue.

 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.9
3 info using node@v4.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart electron-quick-start@1.0.0
6 info start electron-quick-start@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info electron-quick-start@1.0.0 Failed to exec start script
9 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electron-quick-start@1.0.0
11 verbose cwd /home/darin/electron-quick-start
12 error Linux 4.4.0-36-generic
13 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
14 error node v4.5.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error electron-quick-start@1.0.0 start: `electron .`
17 error Exit status 1
18 error Failed at the electron-quick-start@1.0.0 start script 'electron .'.
18 error This is most likely a problem with the electron-quick-start package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron .
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs electron-quick-start
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls electron-quick-start
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by jlord** [comment]
Hmm. @homerzhou what operating system are you using?

**Comment by mralokkp** [comment]
@jlord same issue found here. 
OS Ubuntu 16.04 LTS 64 bit. 
node v6.5.0
npm  v3.10.3

**Comment by nutella** [comment]
Same here with OsX 10.11.6.

**Comment by nutella** [comment]
...solved.

At least on OsX, you must install before electron-prebuilt. See: https://github.com/electron-userland/electron-prebuilt

**Comment by MarshallOfSound** [comment]
@nutella Wait, did you run `npm install` before attempting to run `npm start`?

**Comment by nutella** [comment]
I've tried to run npm install, then npm start. I've tried yesterday on Win 7 and it worked without problems. On OsX doesn't work, also with "sudo" before. I got the error that "electron ." command was not found. So I run: "sudo npm install -g electron", after this, npm install and npm start work well and run the quickstart demo.

**Comment by zeke** [comment]
What @MarshallOfSound said ☝️ 

For info on how to fix your permissions so you don't have to use `sudo`, see this doc: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by Amparose** [comment]
I am also on OSX 10.12.3 (Node 6.10.0 npm 4.4.0) and following the instructions (git clone, npm install && npm start) on the Electron site results in this:

```
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> ([user-location]/electron-quick-start/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> ([user-location]/electron-quick-start/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:570:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
```

I redownloaded / installed / removed node_modules / etc and still doesn't work. Installing electron-prebuilt -g as @nutella suggested fixed it for me as well (I had to re-install electron-quick-start AFTER installing electron-prebuilt too).

This is not very comforting for a novice to follow the [simple] instructions on the site and have it not work. If electron-prebuilt needs to be installed, please update the docs to reflect this.
