### ISSUE TITLE
missing semicolon

### ISSUE THREAD

**Issue by brody182** [electron/electron-quick-start#86]
Why did you leave out all the semicolon on all js files?

**Comment by Haacked** [comment]
Semicolons are optional in ES6. This blog post has a good overview of the discussion about [whether or not to use semicolons](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding).

In the end, there's no real objective "right answer." Use the approach that fits most with the way you want to write code. This project will do the same. :smile:
