### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by Hammerstad** [electron/electron-quick-start#90]
The `README.md` says that this project is available under the CC0 license, but `LICENSE.md` file is the CC1.0-Universal license.

Can either the license or the text in `README.md` be fixed?

**Comment by Hammerstad** [comment]
And while I'm nitpicking, the package.json file also specifies CC1.0. 

Relevant: #8

**Comment by Haacked** [comment]
> The README.md says that this project is available under the CC0 license, but LICENSE.md file is the CC1.0-Universal license.

The License is `CC0 1.0` not `CC1.0`. That means it's the `CC0` license at version `1.0`. So there's no actual conflict here. Note that the README links to the correct license.

And the package.json also correctly specifies `CC0-1.0`.

I don't think there's anything we need to fix here. At most, we could add the version to the license in the README to clear up confusion. @kevinsawicki @zeke any thoughts?
