### ISSUE TITLE
cannot Enter any character in the web console

### ISSUE THREAD

**Issue by SamuraiT** [electron/electron-quick-start#94]
# situation

Open a dev tool and trying to input something in web console, but nothing works.
cannot Enter any character in the web console. What I can do is just paste something from clipboard and Enter `return key`.

[![https://gyazo.com/5dd1328bdd4722f19a88bf116b9632c4]
(https://i.gyazo.com/5dd1328bdd4722f19a88bf116b9632c4.png)](https://gyazo.com/5dd1328bdd4722f19a88bf116b9632c4)

Does anyone have any idea to fix this ?

* Electron version: v1.4.1
* Operating system: OS X El Captian 10.11.4

**Comment by SamuraiT** [comment]
I found out that using tmux causing this phenomenon. actually don't know how it makes happing. However, when I use tmux, the electron's web console does't work , in the meanwhile, when I don't use tmux, it functions!

**Comment by zeke** [comment]
Launching GUI applications from tmux causes various problems; see also https://github.com/electron/electron/issues//916 and https://github.com/electron/electron/issues/3093 for some discussions and possible workarounds.
