### ISSUE TITLE
Windows 10 - npm ERR! weird error 8

### ISSUE THREAD

**Issue by ychoucha** [electron/electron-quick-start#96]
Hello, 

i have windows 10 and i try the exemple, so now i need to understand how to lunche a simple app with electron : 

so now, not working : 

on frech windows 10 installation : 
`
C:\Users\cya20\Downloads\electron-quick-start>npm install && npm start
npm http GET https://registry.npmjs.org/electron
npm http 304 https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/extract-zip
npm http GET https://registry.npmjs.org/electron-download
npm http 304 https://registry.npmjs.org/electron-download
npm http 304 https://registry.npmjs.org/extract-zip
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/fs-extra
npm http GET https://registry.npmjs.org/path-exists
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/nugget
npm http GET https://registry.npmjs.org/home-path
npm http GET https://registry.npmjs.org/sumchecker
npm http GET https://registry.npmjs.org/rc
npm http GET https://registry.npmjs.org/concat-stream/1.5.0
npm http GET https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/yauzl/2.4.1
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/home-path
npm http 304 https://registry.npmjs.org/path-exists
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/nugget
npm http 304 https://registry.npmjs.org/sumchecker
npm http 304 https://registry.npmjs.org/mkdirp/0.5.0
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http 304 https://registry.npmjs.org/concat-stream/1.5.0
npm http GET https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.0.tgz
npm http 304 https://registry.npmjs.org/fs-extra
npm http 304 https://registry.npmjs.org/debug/0.7.4
npm http GET https://registry.npmjs.org/debug/-/debug-0.7.4.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.0.tgz
npm http 200 https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.0.tgz
npm http 200 https://registry.npmjs.org/debug/-/debug-0.7.4.tgz
npm http 304 https://registry.npmjs.org/rc
npm WARN engine path-exists@3.0.0: wanted: {"node":">=4"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http 304 https://registry.npmjs.org/yauzl/2.4.1
npm http GET https://registry.npmjs.org/yauzl/-/yauzl-2.4.1.tgz
npm http 200 https://registry.npmjs.org/yauzl/-/yauzl-2.4.1.tgz
npm http GET https://registry.npmjs.org/es6-promise
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/deep-extend
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/pretty-bytes
npm http GET https://registry.npmjs.org/progress-stream
npm http GET https://registry.npmjs.org/single-line-log
npm http GET https://registry.npmjs.org/throttleit/0.0.2
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/graceful-fs
npm http GET https://registry.npmjs.org/jsonfile
npm http GET https://registry.npmjs.org/klaw
npm http GET https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/ms/0.7.1
npm http 304 https://registry.npmjs.org/deep-extend
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http GET https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/typedarray
npm http 304 https://registry.npmjs.org/throttleit/0.0.2
npm http GET https://registry.npmjs.org/fd-slicer
npm http GET https://registry.npmjs.org/throttleit/-/throttleit-0.0.2.tgz
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/single-line-log
npm http 304 https://registry.npmjs.org/progress-stream
npm http GET https://registry.npmjs.org/single-line-log/-/single-line-log-1.1.2.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http 304 https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz
npm http 200 https://registry.npmjs.org/throttleit/-/throttleit-0.0.2.tgz
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http 200 https://registry.npmjs.org/single-line-log/-/single-line-log-1.1.2.tgz
npm http 304 https://registry.npmjs.org/jsonfile
npm http 304 https://registry.npmjs.org/es6-promise
npm http 304 https://registry.npmjs.org/klaw
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/pretty-bytes
npm WARN engine pretty-bytes@4.0.2: wanted: {"node":">=4"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http GET https://registry.npmjs.org/string-width
npm http GET https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/speedometer
npm http 304 https://registry.npmjs.org/typedarray
npm http GET https://registry.npmjs.org/aws-sign2
npm http GET https://registry.npmjs.org/aws4
npm http GET https://registry.npmjs.org/bl
npm http GET https://registry.npmjs.org/caseless
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/har-validator
npm http GET https://registry.npmjs.org/http-signature
npm http GET https://registry.npmjs.org/is-typedarray
npm http GET https://registry.npmjs.org/isstream
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/qs
npm http GET https://registry.npmjs.org/stringstream
npm http GET https://registry.npmjs.org/tough-cookie
npm http GET https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/string-width
npm WARN engine string-width@2.0.0: wanted: {"node":">=4"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http GET https://registry.npmjs.org/is-fullwidth-code-point
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/fd-slicer
npm http GET https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz
npm http 304 https://registry.npmjs.org/through2
npm http GET https://registry.npmjs.org/pend
npm http 200 https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz
npm http 304 https://registry.npmjs.org/aws-sign2
npm http 304 https://registry.npmjs.org/caseless
npm http 200 https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz
npm http 304 https://registry.npmjs.org/bl
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray
npm http GET https://registry.npmjs.org/process-nextick-args
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/util-deprecate
npm http 304 https://registry.npmjs.org/speedometer
npm http GET https://registry.npmjs.org/xtend
npm http 304 https://registry.npmjs.org/aws4
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/har-validator
npm http 304 https://registry.npmjs.org/http-signature
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/is-typedarray
npm http 304 https://registry.npmjs.org/isstream
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/mime-types
npm http 304 https://registry.npmjs.org/qs
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm http 304 https://registry.npmjs.org/stringstream
npm http 304 https://registry.npmjs.org/is-fullwidth-code-point
npm http 304 https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz
npm http GET https://registry.npmjs.org/form-data/-/form-data-2.0.0.tgz
npm http GET https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz
npm http GET https://registry.npmjs.org/qs/-/qs-6.2.1.tgz
npm http GET https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
npm http GET https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm http GET https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/tough-cookie
npm http 200 https://registry.npmjs.org/form-data/-/form-data-2.0.0.tgz
npm http 200 https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz
npm http 304 https://registry.npmjs.org/pend
npm http 200 https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-2.0.0.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-6.2.1.tgz
npm http 200 https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz
npm http 200 https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz
npm http 200 https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz
npm http 304 https://registry.npmjs.org/process-nextick-args
npm http 304 https://registry.npmjs.org/isarray
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/core-util-is
npm WARN engine is-fullwidth-code-point@2.0.0: wanted: {"node":">=4"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http 304 https://registry.npmjs.org/util-deprecate
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/xtend
npm http GET https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz
npm WARN engine http-signature@1.1.1: wanted: {"node":">=0.8","npm":">=1.3.7"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm WARN engine form-data@2.0.0: wanted: {"node":">= 0.12"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http GET https://registry.npmjs.org/fs.realpath
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/inflight
npm http 200 https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz
npm http 304 https://registry.npmjs.org/object-keys
npm http 304 https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/delayed-stream
npm http GET https://registry.npmjs.org/mime-db
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/asynckit
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http GET https://registry.npmjs.org/jsprim
npm http GET https://registry.npmjs.org/sshpk
npm http GET https://registry.npmjs.org/assert-plus
npm http 304 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/pinkie-promise
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/is-my-json-valid
npm http 304 https://registry.npmjs.org/fs.realpath
npm http 200 https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz
npm http GET https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/asynckit
npm http GET https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz
npm http 304 https://registry.npmjs.org/assert-plus
npm http GET https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz
npm http 304 https://registry.npmjs.org/sshpk
npm http 304 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/jsprim
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/delayed-stream
npm http 200 https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz
npm http 304 https://registry.npmjs.org/brace-expansion
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz
npm http 200 https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz
npm http 304 https://registry.npmjs.org/is-my-json-valid
npm http GET https://registry.npmjs.org/json-schema/0.2.3
npm http GET https://registry.npmjs.org/extsprintf/1.0.2
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/verror/1.3.6
npm http GET https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/json-schema/0.2.3
npm http 304 https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"v0.10.13","npm":"1.3.2"})
npm http 304 https://registry.npmjs.org/extsprintf/1.0.2
npm http 304 https://registry.npmjs.org/verror/1.3.6
npm http GET https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz
npm http GET https://registry.npmjs.org/verror/-/verror-1.3.6.tgz
npm http 200 https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz
npm http 304 https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/asn1
npm http GET https://registry.npmjs.org/dashdash
npm http GET https://registry.npmjs.org/getpass
npm http GET https://registry.npmjs.org/jsbn
npm http GET https://registry.npmjs.org/tweetnacl
npm http GET https://registry.npmjs.org/jodid25519
npm http GET https://registry.npmjs.org/ecc-jsbn
npm http 304 https://registry.npmjs.org/pinkie-promise
npm http GET https://registry.npmjs.org/bcrypt-pbkdf
npm http 200 https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz
npm http 200 https://registry.npmjs.org/verror/-/verror-1.3.6.tgz
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 304 https://registry.npmjs.org/tweetnacl
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 304 https://registry.npmjs.org/dashdash
npm http 304 https://registry.npmjs.org/jodid25519
npm http 304 https://registry.npmjs.org/bcrypt-pbkdf
npm http 304 https://registry.npmjs.org/ecc-jsbn
npm http 304 https://registry.npmjs.org/asn1
npm http 304 https://registry.npmjs.org/getpass
npm http 304 https://registry.npmjs.org/jsbn
npm http GET https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz
npm http GET https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz
npm http GET https://registry.npmjs.org/dashdash/-/dashdash-1.14.0.tgz
npm http GET https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz
npm http GET https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz
npm http GET https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.0.tgz
npm http GET https://registry.npmjs.org/pinkie
npm http GET https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http 200 https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz
npm http 200 https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz
npm http 200 https://registry.npmjs.org/dashdash/-/dashdash-1.14.0.tgz
npm http 200 https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz
npm http 200 https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz
npm http 200 https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.0.tgz
npm http 304 https://registry.npmjs.org/graceful-readlink
npm http 304 https://registry.npmjs.org/pinkie
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/has-flag
npm http 304 https://registry.npmjs.org/has-flag
npm http GET https://registry.npmjs.org/generate-function
npm http GET https://registry.npmjs.org/generate-object-property
npm http GET https://registry.npmjs.org/jsonpointer
npm http 304 https://registry.npmjs.org/generate-function
npm http 304 https://registry.npmjs.org/generate-object-property
npm http 304 https://registry.npmjs.org/jsonpointer
npm http GET https://registry.npmjs.org/is-property
npm http 304 https://registry.npmjs.org/is-property

> electron@1.4.3 postinstall C:\Users\cya20\Downloads\electron-quick-start\node_modules\electron
> node install.js

C:\Users\cya20\Downloads\electron-quick-start\node_modules\electron\node_modules\electron-download\node_modules\nugget\node_modules\single-line-log\node_modules\string-width\index.js:2
const stripAnsi = require('strip-ansi');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\cya20\Downloads\electron-quick-start\node_modules\electron\node_modules\electron-download\node_modules\nugget\node_modules\single-line-log\index.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
unbuild electron@1.4.3
npm ERR! weird error 8
npm ERR! not ok code 0
`

if u have an explainantion please

**Comment by MarshallOfSound** [comment]
>  (current: {"node":"v0.10.13","npm":"1.3.2"})

Your node version is years out of date.  Update to node 4.x or 6.x and it will fix this issue 👍
