### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by maicss** [electron/electron-quick-start#97]
I installed electron already.

![image](https://cloud.githubusercontent.com/assets/9784767/19594075/0f836f68-97b6-11e6-9f73-d0ee71be9ac9.png)

And when I run `npm install`, it still need install electron:

![image](https://cloud.githubusercontent.com/assets/9784767/19594107/3e88b638-97b6-11e6-96c8-b7ba506d0c12.png)

Maybe the reason is I come from China(the gov block plenty foreign website, I use a vpn, and the speed is such terrible...). so, what should I do to avoid the script reinstall electron?

~~And I think the error should be catch, rather than expose it...~~

Thanks.

**Comment by MarshallOfSound** [comment]
@maicss If you can download the electron zip file from the release site.  Just place it in your `~/.electron` directory and `electron-download` will automatically find the zip file there instead of download it.
