### ISSUE TITLE
electron app package error

### ISSUE THREAD

**Issue by amanjobs** [electron/electron-quick-start#98]
I have updated electron package to 1.3.8 using npm install -g electron-prebuilt@latest version --save-dev and it was succesful. Now, when i use npm install, it runs succesfully (i hope, because a new command bar appears after some time). Now, when i run amp start command, this error shows: 

![npm error](https://cloud.githubusercontent.com/assets/22358856/19627194/31b6caa8-995f-11e6-824e-1ca3cd3058ee.PNG)

**Comment by MarshallOfSound** [comment]
Your install of `electron` broke / npm did something funky.

This happens occasionally and can be fixed by deleting the `electron` folder inside your `node_modules` folder and running `npm install` again.

**Comment by Nomia** [comment]
Hi, @amanjobs have you tried @MarshallOfSound 's solution.
My issue has posted at #99 
that is: After running for a while, npm ERR! code ELIFECYCLE

It start successfully. but will crash after a while(mostly one hour).

I'm going to try @MarshallOfSound 's solution out. See if things will work.

**Comment by Nomia** [comment]
I've tried the solution

> This happens occasionally and can be fixed by deleting the electron folder inside your node_modules folder and running npm install again.

My app still crash after running for a while due to the same error.

**Comment by Wolferring** [comment]
enter  \electron-quick-start\node_modules\electron
and then node install.js
and wait
