### ISSUE TITLE
After running for a while,  npm ERR! code ELIFECYCLE, many solution tried.

### ISSUE THREAD

**Issue by Nomia** [electron/electron-quick-start#99]
The issue that happened to me is simillar to #55 and #54 , but I've tried their solution two days ago, no luck.

Detail: 
After my electron app running for a while(mostly one day), the app will crash, and the error shown as image below in the cmd:

![image](https://cloud.githubusercontent.com/assets/1707818/19759497/e80c2066-9c5f-11e6-9c02-aa3b08a1ba26.png)

```
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.4.0 start: `electron src/main.js`
npm ERR! Exit status 3221225477
npm ERR!
npm ERR! Failed at the electronic-wechat@1.4.0 start script 'electron src/main.j
s'.
npm ERR! This is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\apps\wxbot-node\npm-debug.log
```

But there is no npm-debug.log created everytime it crash.

Specifications

```
Version of Electron (run $ electron --version): v1.4.4
OS: Windows 2012
```

I've gooooogled and tried every solution that I found and could think of for a lot of days, got no luck.

Hope you could help me out. It really kills me.

BTW: the program will also crash when running for a while(mostly one day) on my Mac, but the error is different from what's on Windows Server. 

Here is the error on Mac:
![image](https://cloud.githubusercontent.com/assets/1707818/19759740/eab3ab30-9c60-11e6-9f30-a457424986b3.png)

If need anything else to figure this out, feel free reply. Thank u :>

**Comment by Nomia** [comment]
The purpose of my app: 
Embed my website(http://www.example.com) in a BrowserWindow, and "inject" into the website.
The website will refresh after user login and logout, and will receive messages continuously.

I'm wondering whether it's a problem of the memory leak. But I cannot prove it.

**Comment by zeke** [comment]
It look like you may have an object that is being garbage collected.

See this portion of the quick-start app that demonstrates how to create a window in the proper scope to prevent it from being garbage collected: https://github.com/electron/electron-quick-start/blob/master/main.js#L10-L16

**Comment by Nomia** [comment]
Thank u for your reply @zeke 

In my code, I've kept the reference of that window to the instance as a property. Do I have to keep the reference as a "global" variable in the closure?

And is this solution only for Mac, how about the problem that I encountered on Windows? Are they the same issue?

Thanks :>

**Comment by zeke** [comment]
Variables in the global scope will not be garbage collected.

Garbage collection happens on all operating systems, so if this is indeed a garbage collection related bug it should be observable on all platforms.

**Comment by Nomia** [comment]
thx for the quick reply. I'll try this out :>

**Comment by e8315402** [comment]
I have a the very same issue with that. I already set the variable (mainWindow) as a global variable, it still show errors when closing application. Just want to understand what is the main reason. Thanks.

**Comment by codebytere** [comment]
Closing due to issue staleness; if this issue still persists with the latest version of `electron-quick-start` (running Electron `v2.0.0`)please open an issue there with the code causing the crash and I can take a closer look!
